export const STUDENT_NAMES = [
    { authorJapaneseName: '嶋 晏澄', authorEnglishName: 'Azumi Shima' },
    { authorJapaneseName: '竹本誠', authorEnglishName: 'Makoto Takemoto' },
    { authorJapaneseName: '宮﨑那奈子', authorEnglishName: 'Nanako Miyazaki' },
    { authorJapaneseName: '後藤朋美', authorEnglishName: 'Tomomi Goto' },
    { authorJapaneseName: '浅井睦', authorEnglishName: 'Mutsushi Asai' },
    { authorJapaneseName: '猪﨑康世', authorEnglishName: 'Kosei Izaki' },
    { authorJapaneseName: '上田麟太朗', authorEnglishName: 'Rintaro UEDA' },
    { authorJapaneseName: '璃月ゆあ', authorEnglishName: 'Yua Riduki' },
    { authorJapaneseName: 'カワイタケシ', authorEnglishName: 'KAWAI Takeshi' },
    { authorJapaneseName: '菊田佳恵', authorEnglishName: 'Yoshie Kikuta' },
    { authorJapaneseName: '三波蒼菜', authorEnglishName: 'aona minami' },
    { authorJapaneseName: '志村翔太', authorEnglishName: 'Shota Shimura' },
    { authorJapaneseName: 'ジョン ジユン', authorEnglishName: 'JUNG Jieyun' },
    { authorJapaneseName: '對中優', authorEnglishName: 'Masaru Tainaka' },
    { authorJapaneseName: '徳保晴人', authorEnglishName: 'Tokubo Haruto' },
    { authorJapaneseName: '成瀬陽太', authorEnglishName: 'Santa NARUSE' },
    { authorJapaneseName: 'バク ソミン', authorEnglishName: 'BAK Somin' },
    { authorJapaneseName: '橋本正隆', authorEnglishName: 'Masataka Hashimoto' },
    { authorJapaneseName: '松井美緒', authorEnglishName: 'Mio Matsui' },
    { authorJapaneseName: '山口結子', authorEnglishName: 'Yuiko Yamaguchi' },
    { authorJapaneseName: 'ジョアンナ　リュ', authorEnglishName: 'Joanna LYU' }
]; 