export const EVENTS = [
    {
        "eventName": "開会式",
        "day": "Friday",
        "time": "13:00-13:30",
        "place": "メインステージ(4F)"
    },
    {
        "eventName": "IAMAS JUNCTION",
        "exhibitors": "成瀬陽太・徳保晴人・松井美緒",
        "day": "Friday",
        "time": "14:00-14:45",
        "place": "メインステージ(4F)",
        "content": "IAMASで扱われている研究分野は多様であるゆえに、学生間でも他の人の研究は知っているようで知らないものです。異なる目的地へ向かう者が行き交いながらも合流する交通の要所「JUNCTION」のように、修士二年生の出展者同士が談話を通して互いの研究テーマについて話し合うIAMAS JUNCTIONを開催します。",
        "student1": "Santa Naruse",
        "student2": "Haruto Tokubo",
        "student3": "Mio Matsui"
    },
    {
        "eventName": "IAMAS JUNCTION",
        "exhibitors": "橋本正隆・上田麟太朗",
        "day": "Friday",
        "time": "15:00-15:45",
        "place": "メインステージ(4F)",
        "content": "IAMASで扱われている研究分野は多様であるゆえに、学生間でも他の人の研究は知っているようで知らないものです。異なる目的地へ向かう者が行き交いながらも合流する交通の要所「JUNCTION」のように、修士二年生の出展者同士が談話を通して互いの研究テーマについて話し合うIAMAS JUNCTIONを開催します。",
        "student1": "Masataka Hashimoto",
        "student2": "Rintaro UEDA"
    },
    {
        "eventName": "IAMAS JUNCTION",
        "exhibitors": "嶋晏澄・竹本誠・宮崎那奈子",
        "day": "Friday",
        "time": "16:00-16:45",
        "place": "メインステージ(4F)",
        "content": "IAMASで扱われている研究分野は多様であるゆえに、学生間でも他の人の研究は知っているようで知らないものです。異なる目的地へ向かう者が行き交いながらも合流する交通の要所「JUNCTION」のように、修士二年生の出展者同士が談話を通して互いの研究テーマについて話し合うIAMAS JUNCTIONを開催します。",
        "student1": "Azumi Shima",
        "student2": "Makoto Takemoto",
        "student3": "Nanako Miyazaki"
    },
    {
        "eventName": "IAMAS JUNCTION",
        "exhibitors": "三波蒼菜・後藤朋美・BAK SOMIN",
        "day": "Friday",
        "time": "17:00-17:45",
        "place": "メインステージ(4F)",
        "content": "IAMASで扱われている研究分野は多様であるゆえに、学生間でも他の人の研究は知っているようで知らないものです。異なる目的地へ向かう者が行き交いながらも合流する交通の要所「JUNCTION」のように、修士二年生の出展者同士が談話を通して互いの研究テーマについて話し合うIAMAS JUNCTIONを開催します。",
        "student1": "aona minami",
        "student2": "Tomomi Goto",
        "student3": "BAK Somin"
    },
    {
        "eventName": "クリティカルサイクリング　―寒中ライド―",
        "exhibitors": "クリティカル・サイクリング",
        "day": "Saturday",
        "time": "8:00-10:30",
        "place": "ソフトピア・ジャパン・センタービル 北玄関前　\n(1F)",
        "content": "来る2月22日にクリティカル・サイクリングと運動体設計の共催による早朝耐寒ライドを行います。これはIAMASの卒展イベントとして行われ、どなたでもご参加いただけます。今年度はIAMAS周辺のゴミを拾いながらサイクリングをします。",
        "participant1_name": "クリティカル・サイクリング",
        "participant1_profile": "クリティカル・サイクリング（Critical Cycling）は、サイクリングを楽しみ、その批評性を探求する任意グループです。岐阜県大垣市にあるIAMAS（情報科学芸術大学院大学）を中心に2016年4月より活動をしています。"
    },
    {
        "eventName": "プロジェクト研究：口頭発表",
        "exhibitors": "体験拡張表現プロジェクト・Collaborative Design Research Project・場所・感覚・メディア・テクノロジーの〈解釈学〉",
        "day": "Saturday",
        "time": "11:00-12:00",
        "place": "レセプションルーム大特設ステージ(12F)",
        "content": "プロジェクト研究はIAMASにおいて修士研究を行うための枠組みとしての役割を果たす重要な科目として位置付けられています。メディア表現の社会的な意味をはかり、社会へ向けた成果の発信や外部との連携を強く意識し、領域横断的に運営されます。本イベントでは今年度の各プロジェクト研究における成果について口頭で発表します。",
        "participant1_name": "体験拡張表現プロジェクト",
        "participant1_profile": "https://www.iamas.ac.jp/master_projects/enhanced-experience-expression/",
        "participant2_name": "Collaborative Design Research Project",
        "participant2_profile": "https://www.iamas.ac.jp/master_projects/collaborative-design-research/",
        "participant3_name": "場所・感覚・メディア",
        "participant3_profile": "https://www.iamas.ac.jp/master_projects/place-sense-media/",
        "participant4_name": "テクノロジーの〈解釈学〉",
        "participant4_profile": "https://www.iamas.ac.jp/master_projects/interpretive-practices-of-technology/"
    },
    {
        "eventName": "なぜ私たちは自らの校舎をディストピアと呼ぶのか：トーク",
        "exhibitors": "志村翔太・坂根大悟・赤松正行",
        "day": "Saturday",
        "time": "12:00-13:00",
        "place": "メインステージ(4F)",
        "content": "梶原岐阜県知事時代の箱物行政政策によって誕生したセンタービルをはじめとする建築群と、運動体設計プロジェクト内で昨年実施したIAMAS旧校舎や門入集落へのリサーチ、荒川修作に関する調査、さらに2024年10月に訪問した磯崎新による奈義町美術館（「建築と作品が一体化した公共建築」）と養老天命反転地の比較を関連付け、「エッジ」の視点から考察を行います。ゲストとして東京藝術大学メディア映像M1の坂根大悟さんをお迎えし、彼の専門である鉄道史の視点から大垣と箱物について話題提供をいただきます。午後には自転車に乗って実際に養老へ向かい、養老天命反転地を訪問しつつ、センタービルが街の外れから見える境界（エッジ）を探ります。",
        "student1": "Shota Shimura",
        "participant1_name": "坂根大悟",
        "participant1_profile": "1995年旧大宮市出身。学習院大学文学部史学科卒業。東京藝術大学映像研究科メディア映像専攻修士１年。その土地の持つ歴史や都市を題材に、相反するものが共存しながら、複数の可能性が同時存在する「陰陽太極図的メディア空間」を探求しつつ、立体、映像、中間媒介物を組み合わせ、作品を制作。主な展示歴に2023 年さいたま国際芸術祭公募作品展、2022年六本木アートナイト・オープンコールプロジェクトなど。",
        "participant2_name": "赤松正行",
        "participant2_status": "IAMAS教授",
        "participant2_profile": "1961年兵庫県生まれ。メディア作家。京都市立芸術大学大学院美術研究科修了、 博士（美術）。インタラクティブな音楽や映像作品を制作、近年はモビリティとリアリティをテーマにテクノロジーが人と社会へ及ぼす影響を制作を通して考察している。代表作は書籍「Maxの教科書」、「iOSの教科書」、アプリ「Spatial Poetry」、「セカイカメラ（頓智ドット）」、インスタレーション「ウロボロスのトーチ」 など。"
    },
    {
        "eventName": "ガムラン演奏",
        "exhibitors": "IAMASガムラン部",
        "day": "Saturday",
        "time": "12:30-13:00",
        "place": "信長広場(1F)",
        "content": "今回のIAMAS2025での演奏は、IAMASの有志学生のみならず、学外の方にも参加していただくIAMASガムラン部の今年度の集大成となる演奏です。ガムランが織りなす高次倍音を豊富に含んだ音色と、一人一人のシンプルなパートが重なり合い生み出される豊かなリズム&メロディ、流動的で開かれた時間、空間をじっくりとお楽しみください。",
        "participant1_name": "IAMASガムラン部",
        "participant1_profile": "IAMASガムラン部は、岡戸香里先生のご指導のもと、IAMASの有志学生のみならず、岐阜県内外の方も含めたメンバーで構成されています。IAMAS外部の方の参加を心よりお待ちしております。ガムランに興味のある方は是非お声がけください。"
    },
    {
        "eventName": "プロジェクト研究：展示コアタイム",
        "exhibitors": "体験拡張表現プロジェクト・福祉の技術プロジェクト3・The Art of Listening・Extreme Biologies・Collaborative Design Research Project・テクノロジーの〈解釈学〉",
        "day": "Saturday",
        "time": "13:00-14:00",
        "place": "レセプションルーム大(12F)",
        "content": "プロジェクト研究はIAMASにおいて修士研究を行うための枠組みとしての役割を果たす重要な科目として位置付けられています。メディア表現の社会的な意味をはかり、社会へ向けた成果の発信や外部との連携を強く意識し、領域横断的に運営されます。本イベントでは今年度の各プロジェクト研究における成果について展示します。",
        "participant1_name": "体験拡張表現プロジェクト",
        "participant1_profile": "https://www.iamas.ac.jp/master_projects/enhanced-experience-expression/",
        "participant2_name": "福祉の技術プロジェクト",
        "participant2_profile": "https://www.iamas.ac.jp/master_projects/collaborative-design-research/",
        "participant3_name": "The Art of Listening",
        "participant3_profile": "https://www.iamas.ac.jp/master_projects/the-art-of-listening/",
        "participant4_name": "Extreme Biologies",
        "participant4_profile": "https://www.iamas.ac.jp/master_projects/extreme-biologies/",
        "participant5_name": "Collaborative Design Research Project",
        "participant5_profile": "https://www.iamas.ac.jp/master_projects/collaborative-design-research/",
        "participant6_name": "テクノロジーの〈解釈学〉",
        "participant6_profile": "https://www.iamas.ac.jp/master_projects/interpretive-practices-of-technology/"
    },
    {
        "eventName": "ジェンダーじゃない話をしよう！",
        "exhibitors": "菅実花・松井茂・小林史佳・早田仁知\n・髙岸航平(ファシリテーター)",
        "day": "Saturday",
        "time": "14:00-15:30",
        "place": "メインステージ(4F)",
        "content": "これまでIAMASでジェンダーに関する議論はあまり行われてきませんでした。男性名詞や女性名詞がある言語って、どんなふうに世界を捉えているのかな？男らしさ・女らしさの意識に影響するのかな？そんな疑問から出発した勉強会の特別編として、IAMASでジェンダーの議論をすることについて考えます。",
        "participant1_name": "菅実花",
        "participant1_status": "IAMAS准教授",
        "participant1_profile": "美術作家。情報科学芸術大学院大学准教授および京都芸術大学大学院(通信教育)写真映像領域特任准教授。大衆的な写真文化と、人形の文脈を交錯させた写真・映像作品を手がけ「人間と非人間の境界」を問う。共著に2018年『〈妊婦〉アート論』(青弓社)。VOCA展2020奨励賞受賞。",
        "participant2_name": "松井茂",
        "participant2_status": "IAMAS教授",
        "participant2_profile": "著書に『虚像培養芸術論　アートとテレビジョンの想像力』（フィルムアート社、2021年）。川崎弘二との共著書に『坂本龍一のメディア・パフォーマンス　マス・メディアの中の芸術家像』（同、2023年）。伊村靖子との共編著に『虚像の時代　東野芳明美術批評選』（河出書房新社、2013年）。",
        "participant3_name": "小林史佳",
        "participant3_status": "IAMAS修士1年",
        "participant3_profile": "餅の形は四角い切り餅、それをトースターで焼いて砂糖醤油をつけて食べる家庭で育つ。一人暮らしを始めてからはトースターを置く場所がないため、水の入った容器に餅を入れて電子レンジで温める。それを汁に入れてお雑煮のようにして食べている。季節は問わない。",
        "participant4_name": "早田仁知",
        "participant4_status": "IAMAS修士1年",
        "participant4_profile": "2001年生まれ。東京外大言語文化学部ヒンディー語専攻卒業。学部時代には音声学を専門にし、日本語とヒンディー語のオノマトペ対照をテーマに研究。多言語社会であるインド・デリー大学への交換留学を経て、現在は言語の消滅・忘却に関する研究と制作に取り組む。学外では作詞作曲家として楽曲制作等の活動も行っている。",
        "participant5_name": "髙岸航平",
        "participant5_status": "IAMAS修士1年",
        "participant5_profile": "学部の専門は漆工と木工。成層圏で漆造形作品を撮影する「宙漆プロジェクト」代表。現在は生成AIを通した芸術教育について研究に取り組む。"
    },
    {
        "eventName": "IAMAS JUNCTION",
        "exhibitors": "山口結子・JUNG JIEYUN・菊田佳恵",
        "day": "Saturday",
        "time": "16:00-16:45",
        "place": "メインステージ(4F)",
        "content": "IAMASで扱われている研究分野は多様であるゆえに、学生間でも他の人の研究は知っているようで知らないものです。異なる目的地へ向かう者が行き交いながらも合流する交通の要所「JUNCTION」のように、修士二年生の出展者同士が談話を通して互いの研究テーマについて話し合うIAMAS JUNCTIONを開催します。",
        "student1": "Yuiko Yamaguchi",
        "student2": "JUNG Jieyun",
        "student3": "Yoshie Kikuta"
    },
    {
        "eventName": "NxPC.Live vol.72 唵楽と影像",
        "day": "Saturday",
        "time": "17:00-20:00",
        "place": "セミナーホール(1F)",
        "content": "NxPC.Labは、クラブやライブにおけるアーティストと観客の相互作用によってもたらされる場の臨場感を拡大し、ネットへも拡散させるためのメディアテクノロジーの実現を目指した研究機関です。",
        "participant1_name": "Record PrayerPXL(葊-iori / 松井光久)",
        "participant1_profile": "PhoneTacte という自作楽器を演奏する。指先と足先の繊細な動きで、音と身体が融合する新感覚演奏。",
        "participant2_name": "ニチウシオーハシ(想多二千 / うしおひまり / オーハシ)",
        "participant2_profile": "二人に見えて三人である。とある世界認識方法と景色分解能について。",
        "participant3_name": "Nomad Sentinel(KOUSEI / 葊 - iori)",
        "participant3_profile": "Nomad Sentinel was born from a series of visual creation experiments and has gradually expanded into installation art, VR art, and interactive art.",
        "participant4_name": "hrx",
        "participant4_profile": "乱数発生器は観客に反応するのか？乱数発生器が観客の情動に反応するというアイデアを実証するための実験的パフォーマンス"
    },
    {
        "eventName": "なぜ私たちは自らの校舎をディストピアと呼ぶのか ：サイクリングツアー",
        "exhibitors": "志村翔太・坂根大悟・赤松正行",
        "day": "Sunday",
        "time": "7:00-10:30",
        "place": "ソフトピア・ジャパン・センタービル 北玄関前(1F)",
        "content": "梶原岐阜県知事時代の箱物行政政策によって誕生したセンタービルをはじめとする建築群と、運動体設計プロジェクト内で昨年実施したIAMAS旧校舎や門入集落へのリサーチ、荒川修作に関する調査、さらに2024年10月に訪問した磯崎新による奈義町美術館（「建築と作品が一体化した公共建築」）と養老天命反転地の比較を関連付け、「エッジ」の視点から考察を行います。ゲストとして東京藝術大学メディア映像M1の坂根大悟さんをお迎えし、彼の専門である鉄道史の視点から大垣と箱物について話題提供をいただきます。午後には自転車に乗って実際に養老へ向かい、養老天命反転地を訪問しつつ、センタービルが街の外れから見える境界（エッジ）を探ります。",
        "student1": "Shota Shimura",
        "participant1_name": "坂根大悟",
        "participant1_profile": "1995年旧大宮市出身。学習院大学文学部史学科卒業。東京藝術大学映像研究科メディア映像専攻修士１年。その土地の持つ歴史や都市を題材に、相反するものが共存しながら、複数の可能性が同時存在する「陰陽太極図的メディア空間」を探求しつつ、立体、映像、中間媒介物を組み合わせ、作品を制作。主な展示歴に2023 年さいたま国際芸術祭公募作品展、2022年六本木アートナイト・オープンコールプロジェクトなど。",
        "participant2_name": "赤松正行",
        "participant2_status": "IAMAS教授",
        "participant2_profile": "1961年兵庫県生まれ。メディア作家。京都市立芸術大学大学院美術研究科修了、 博士（美術）。インタラクティブな音楽や映像作品を制作、近年はモビリティとリアリティをテーマにテクノロジーが人と社会へ及ぼす影響を制作を通して考察している。代表作は書籍「Maxの教科書」、「iOSの教科書」、アプリ「Spatial Poetry」、「セカイカメラ（頓智ドット）」、インスタレーション「ウロボロスのトーチ」 など。"
    },
    {
        "eventName": "プロジェクト研究：口頭発表",
        "exhibitors": "運動体設計・The Art of Listening・Extreme Biologies",
        "day": "Sunday",
        "time": "11:00-12:00",
        "place": "レセプションルーム大特設ステージ(12F)",
        "content": "プロジェクト研究はIAMASにおいて修士研究を行うための枠組みとしての役割を果たす重要な科目として位置付けられています。メディア表現の社会的な意味をはかり、社会へ向けた成果の発信や外部との連携を強く意識し、領域横断的に運営されます。本イベントでは今年度の各プロジェクト研究における成果について口頭で発表します。",
        "participant1_name": "運動体設計",
        "participant1_profile": "https://www.iamas.ac.jp/master_projects/visions-in-motion/",
        "participant2_name": "The Art of Listening",
        "participant2_profile": "https://www.iamas.ac.jp/master_projects/the-art-of-listening/",
        "participant3_name": "Extreme Biologies",
        "participant3_profile": "https://www.iamas.ac.jp/master_projects/extreme-biologies/"
    },
    {
        "eventName": "IAMAS JUNCTION",
        "exhibitors": "對中優・カワイタケシ・猪崎康世",
        "day": "Sunday",
        "time": "12:00-12:45",
        "place": "メインステージ(4F)",
        "content": "IAMASで扱われている研究分野は多様であるゆえに、学生間でも他の人の研究は知っているようで知らないものです。異なる目的地へ向かう者が行き交いながらも合流する交通の要所「JUNCTION」のように、修士二年生の出展者同士が談話を通して互いの研究テーマについて話し合うIAMAS JUNCTIONを開催します。",
        "student1": "Masaru Tainaka",
        "student2": "KAWAI Takeshi",
        "student3": "Kosei Izaki"
    },
    {
        "eventName": "プロジェクト研究：展示コアタイム",
        "exhibitors": "体験拡張表現プロジェクト・福祉の技術プロジェクト3・The Art of Listening・Extreme Biologies・Collaborative Design Research Project・テクノロジーの〈解釈学〉",
        "day": "Sunday",
        "time": "13:00-14:00",
        "place": "レセプションルーム大(12F)",
        "content": "プロジェクト研究はIAMASにおいて修士研究を行うための枠組みとしての役割を果たす重要な科目として位置付けられています。メディア表現の社会的な意味をはかり、社会へ向けた成果の発信や外部との連携を強く意識し、領域横断的に運営されます。本イベントでは今年度の各プロジェクト研究における成果について展示します。",
        "participant1_name": "体験拡張表現プロジェクト",
        "participant1_profile": "https://www.iamas.ac.jp/master_projects/enhanced-experience-expression/",
        "participant2_name": "福祉の技術プロジェクト",
        "participant2_profile": "https://www.iamas.ac.jp/master_projects/collaborative-design-research/",
        "participant3_name": "The Art of Listening",
        "participant3_profile": "https://www.iamas.ac.jp/master_projects/the-art-of-listening/",
        "participant4_name": "Extreme Biologies",
        "participant4_profile": "https://www.iamas.ac.jp/master_projects/extreme-biologies/",
        "participant5_name": "Collaborative Design Research Project",
        "participant5_profile": "https://www.iamas.ac.jp/master_projects/collaborative-design-research/",
        "participant6_name": "テクノロジーの〈解釈学〉",
        "participant6_profile": "https://www.iamas.ac.jp/master_projects/interpretive-practices-of-technology/"
    },
    {
        "eventName": "ポスト言語学：「言葉とは何か」とは何か",
        "exhibitors": "早田仁知・伊藤雄馬・マユンキキ・髙岸航平",
        "day": "Sunday",
        "time": "14:00-15:30",
        "place": "メインステージ(4F)",
        "content": "「言語の消滅は喪失しか起こさないのか？」「そもそも言語は本当に消滅するものなのか？」「私たちの言語は『構造』に還元されるしかないのか？」「言語学における言語とは何か？それは昔と同じままでいいだろうか？」現代の言語学の限界と可能性を探り、新しい言語学を切り拓きます。",
        "participant1_name": "伊藤雄馬",
        "participant1_status": "言語学者",
        "participant1_profile": "1986年生。タイ・ラオスで話されるムラブリ語を中心にフィールドワークを行う。大学教員を経て、2020年から独立。ムラブリ語が母語の次に得意。2022年公開のドキュメンタリー映画『森のムラブリ』(監督:金子遊)に出演し、現地コーディネーター、字幕翻訳を担当。著書に『ムラブリ　文字も暦も持たない狩猟採集民から言語学者が教わったこと』（集英社インターナショナル）、『人類学者と言語学者が森に入って考えたこと』（教育評論社、共著）など。",
        "participant2_name": "マユンキキ",
        "participant2_profile": "1982年北海道生まれ。アイヌの伝統歌を歌う「マレウレウ」「アペトゥンペ」のメンバー。2021年よりソロ活動開始。2018年より、自身のルーツと美意識に纏わる興味・関心からアイヌ女性の伝統的な文身「シヌイェ」の研究を開始。現代におけるアイヌの存在を、あくまで個人としての観点から探求し、表現している。",
        "participant3_name": "早田仁知",
        "participant3_status": "IAMAS修士1年",
        "participant3_profile": "2001年生まれ。東京外大言語文化学部ヒンディー語専攻卒業。学部時代には音声学を専門にし、日本語とヒンディー語のオノマトペ対照をテーマに研究。多言語社会であるインド・デリー大学への交換留学を経て、現在は言語の消滅・忘却に関する研究と制作に取り組む。学外では作詞作曲家として楽曲制作等の活動も行っている。",
        "participant4_name": "髙岸航平",
        "participant4_status": "IAMAS修士1年",
        "participant4_profile": "学部の専門は漆工と木工。成層圏で漆造形作品を撮影する「宙漆プロジェクト」代表。現在は生成AIを通した芸術教育について研究に取り組む。"
    },
    {
        "eventName": "技術/手法の実験の積み重ねから生まれる視覚表現を紐解く",
        "exhibitors": "成瀬陽太・橋本麦・石川将也",
        "day": "Sunday",
        "time": "16:00-17:30",
        "place": "メインステージ(4F)",
        "content": "視覚表現は、幅広い領域の技術/手法を実験的に取り入れながら発展し、新たな形が探索されています。本イベントでは、映像表現、インスタレーション作品、視覚認知の研究など、領域を横断しながら視覚表現を探索するグラフィックデザイナー/研究者の石川将也氏と映像作家/ツール開発者の橋本麦氏をお招きし、IAMASにて視覚認知に関する視覚表現について研究する成瀬陽太の3人で「実験の積み重ねから生まれる視覚表現」についてトークを行います。",
        "student1": "Santa Naruse",
        "participant1_name": "橋本麦",
        "participant1_status": "映像作家",
        "participant1_profile": "実験映像やハッカー文化に影響を受け、CGIからコマ撮りアニメーション、ミュージック・ビデオ、インタラクティブ作品まで、多岐に渡って個人で制作を続けてきた。さまざまな表現手法の実験の積み重ねにより、多様な視覚表象のスタイルを模索している。",
        "participant2_name": "石川将也",
        "participant2_status": "グラフィックデザイナー / 研究者",
        "participant2_profile": "1980年生まれ。慶應義塾大学大学院 政策・メディア研究科 修了。佐藤雅彦研究室を経て、2019年までクリエイティブグループ「ユーフラテス」に所属。20年独立。視覚表現の開発と、視覚認知の研究を基点に、グラフィックデザイン、映像、インスタレーション、科学玩具とそれを用いたワークショップの開発など、さまざま活動している。代表作に「factory of dream」「そうとしかみえない」「歩くの歌」（Eテレ2355 / 0655）「ねじねじの歌」「クッキー型の型の歌」（ピタゴラスイッチ）、「Layers Act」「光のレイヤー」「マグネタクトアニマル」「四角が行く」「開け箱」など。2024年より U-NEXT Kids オリジナルコンテンツ「ねむるま えほん」「うご工作」の監督として企画の立案から携わっている。"
    },
    {
        "eventName": "レセプション",
        "day": "Sunday",
        "time": "18:00-",
        "place": "こみゅれす 美濃味匠(1F)",
        "content": "来場者の皆さまと学生・教職員との親睦を深めるためのパーティ。どなたでもお気軽にご参加ください。"
    },
    {
        "eventName": "IAMAS JUNCTION",
        "exhibitors": "浅井睦・璃月ゆあ",
        "day": "Monday",
        "time": "12:00-12:45",
        "place": "メインステージ(4F)",
        "content": "IAMASで扱われている研究分野は多様であるゆえに、学生間でも他の人の研究は知っているようで知らないものです。異なる目的地へ向かう者が行き交いながらも合流する交通の要所「JUNCTION」のように、修士二年生の出展者同士が談話を通して互いの研究テーマについて話し合うIAMAS JUNCTIONを開催します。",
        "student1": "Mutsushi Asai",
        "student2": "Yua Riduki"
    },
    {
        "eventName": "プロジェクト研究：展示コアタイム",
        "exhibitors": "体験拡張表現プロジェクト・福祉の技術プロジェクト3・The Art of Listening・Extreme Biologies・Collaborative Design Research Project・テクノロジーの〈解釈学〉",
        "day": "Monday",
        "time": "13:00-14:00",
        "place": "レセプションルーム大(12F)",
        "content": "プロジェクト研究はIAMASにおいて修士研究を行うための枠組みとしての役割を果たす重要な科目として位置付けられています。メディア表現の社会的な意味をはかり、社会へ向けた成果の発信や外部との連携を強く意識し、領域横断的に運営されます。本イベントでは今年度の各プロジェクト研究における成果について展示します。",
        "participant1_name": "体験拡張表現プロジェクト",
        "participant1_profile": "https://www.iamas.ac.jp/master_projects/enhanced-experience-expression/",
        "participant2_name": "福祉の技術プロジェクト",
        "participant2_profile": "https://www.iamas.ac.jp/master_projects/collaborative-design-research/",
        "participant3_name": "The Art of Listening",
        "participant3_profile": "https://www.iamas.ac.jp/master_projects/the-art-of-listening/",
        "participant4_name": "Extreme Biologies",
        "participant4_profile": "https://www.iamas.ac.jp/master_projects/extreme-biologies/",
        "participant5_name": "Collaborative Design Research Project",
        "participant5_profile": "https://www.iamas.ac.jp/master_projects/collaborative-design-research/",
        "participant6_name": "テクノロジーの〈解釈学〉",
        "participant6_profile": "https://www.iamas.ac.jp/master_projects/interpretive-practices-of-technology/"
    },
    {
        "eventName": "IAMASのはじまり、坂根厳夫先生を偲んで",
        "exhibitors": "岩井俊雄・ 山元史朗・ クワクボリョウタ(聞き手)",
        "day": "Monday",
        "time": "16:00-17:30",
        "place": "メインステージ(4F)",
        "content": "IAMAS（岐阜県立国際情報科学芸術アカデミー）の設立に尽力され、1996年から2002年度まで初代学長を務められた坂根厳夫名誉学長が、2024年4月28日にご逝去されました。\n坂根先生は中国・青島で生まれ、東京大学工学部建築学科および大学院修士課程を修了。その後、朝日新聞家庭部・科学部記者や学芸部編集委員を経て、慶應義塾大学環境情報学部教授。1996年から2002年までIAMASの学長（後に名誉学長）を務められました。同時にエッシャーに代表される幾何学的アートや現象アート、メディア・アートの研究・著述・翻訳など、多彩な分野で活躍されました。\n今回のトークイベントでは、開学当時の坂根先生をご存じの3名のゲストをお招きし、「IAMASの創設者としての坂根先生」を共に振り返ります。改めて先生の足跡を偲びながら、当時のIAMASが掲げていたビジョンやエピソードを語り合う機会にしたいと思います。",
        "participant1_name": "岩井俊雄\n",
        "participant1_profile": "1962年愛知県西尾市吉良町生まれ。筑波大学大学院芸術研究科修了。子どもの頃に母親から「もうおもちゃは買いません」と言われ、ものづくりに目覚める。大学時代に実験アニメーション制作を始め、1985年に、驚き盤やゾートロープなど19世紀の映像装置を進化させた《時間層II》で「第17回現代日本美術展」大賞を最年少受賞。その後、メディアアーティストとして国内外の美術館でコンピュータを使ったインタラクティブな作品を多数発表しつつ、『ウゴウゴルーガ』などのテレビ番組やゲームソフト制作などで幅広く活動を展開する。2000年代に娘との手作りおもちゃをきっかけに絵本制作を始め、「100かいだてのいえ」シリーズ（偕成社）が大ヒット。子どもや親子にものづくりの楽しさを伝えるワークショップを多数開催している。",
        "participant2_name": "山元史朗\n",
        "participant2_profile": "1970年生まれ。テクニカルディレクター、日本大学芸術学部非常勤講師。筑波大学大学院芸術研究科修了後、IAMAS、YCAMの設立に携わり、日本科学未来館で企画展・巡回展の制作を担当。2012年よりフリーランスのテクニカルディレクターとして、メディアアートを中心に展示技術の開発やテクニカルディレクションを手がける。現在、2026年開館予定の「MoN Takanawa」の設立準備にも携わっている。",
        "participant3_name": "クワクボリョウタ(聞き手)"
    },
    {
        "eventName": "IAMASONIC 2025 - pit in",
        "day": "Monday",
        "time": "19:00-21:00",
        "place": "水上ステージ（雨天時セミナーホール）",
        "content": "IAMASONIC 2025-pit inは、IAMAS卒業生が次のステージへと飛躍するための「補給」となる場です。卒業制作展のテーマ「苦悩と誠実」が示すように、ものづくりは生涯続くレースのようなもの。本イベントでは、その過程における「pit-in」として、より良いパフォーマンスを維持し、新たな挑戦へと進むための機会を提供します。IAMASに関わるクリエイターたちが、ここでエネルギーを蓄え、再び走り出すことを願っています。\n"
    }
];