export const EVENTS = [
    {
        "eventName": "IAMAS JUNCTION",
        "exhibitors": "成瀬・徳保・松井美",
        "day": "Friday",
        "time": "14:00-",
        "content": "IAMASで扱われている研究分野は多様であるゆえに、学生間でも他の人の研究は知っているようで知らないものです。異なる目的地へ向かう者が行き交いながらも合流する交通の要所「JUNCTION」のように、修士二年生の出展者同士が談話を通して互いの研究テーマについて話し合うIAMAS JUNCTIONを開催します。",
        "student1": "Sanata NARUSE",
        "student2": "Tokubo Haruto",
        "student3": "Mio Matsui",
        "participant1_name": "",
        "participant1_status": "",
        "participant1_profile": "",
        "participant2_name": "",
        "participant2_status": "",
        "participant2_profile": "",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "IAMAS JUNCTION",
        "exhibitors": "橋本正隆・上田麟太朗",
        "day": "Friday",
        "time": "15:00-",
        "content": "IAMASで扱われている研究分野は多様であるゆえに、学生間でも他の人の研究は知っているようで知らないものです。異なる目的地へ向かう者が行き交いながらも合流する交通の要所「JUNCTION」のように、修士二年生の出展者同士が談話を通して互いの研究テーマについて話し合うIAMAS JUNCTIONを開催します。",
        "student1": "Masataka Hashimoto",
        "student2": "Rintaro UEDA",
        "student3": "",
        "participant1_name": "",
        "participant1_status": "",
        "participant1_profile": "",
        "participant2_name": "",
        "participant2_status": "",
        "participant2_profile": "",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "IAMAS JUNCTION",
        "exhibitors": "嶋・竹本・宮崎",
        "day": "Friday",
        "time": "16:00-",
        "content": "IAMASで扱われている研究分野は多様であるゆえに、学生間でも他の人の研究は知っているようで知らないものです。異なる目的地へ向かう者が行き交いながらも合流する交通の要所「JUNCTION」のように、修士二年生の出展者同士が談話を通して互いの研究テーマについて話し合うIAMAS JUNCTIONを開催します。",
        "student1": "Azumi Shima",
        "student2": "Makoto Takemoto",
        "student3": "Nanako Miyazaki",
        "participant1_name": "",
        "participant1_status": "",
        "participant1_profile": "",
        "participant2_name": "",
        "participant2_status": "",
        "participant2_profile": "",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "IAMAS JUNCTION",
        "exhibitors": "小南・後藤・ソミン",
        "day": "Friday",
        "time": "17:00-",
        "content": "IAMASで扱われている研究分野は多様であるゆえに、学生間でも他の人の研究は知っているようで知らないものです。異なる目的地へ向かう者が行き交いながらも合流する交通の要所「JUNCTION」のように、修士二年生の出展者同士が談話を通して互いの研究テーマについて話し合うIAMAS JUNCTIONを開催します。",
        "student1": "aona minami",
        "student2": "Tomomi Goto",
        "student3": "BAK Somin",
        "participant1_name": "",
        "participant1_status": "",
        "participant1_profile": "",
        "participant2_name": "",
        "participant2_status": "",
        "participant2_profile": "",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "",
        "exhibitors": "",
        "day": "Saturday",
        "time": "10:00-12:00",
        "content": "",
        "student1": "",
        "student2": "",
        "student3": "",
        "participant1_name": "",
        "participant1_status": "",
        "participant1_profile": "",
        "participant2_name": "",
        "participant2_status": "",
        "participant2_profile": "",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "なぜ私たちは自らの校舎をディストピアと呼ぶのか",
        "exhibitors": "志村翔太・坂根大悟・赤松正行",
        "day": "Saturday",
        "time": "10:00-12:00",
        "content": "梶原岐阜県知事時代の箱物行政政策によって誕生したセンタービルをはじめとする建築群と、運動体設計プロジェクト内で昨年実施したIAMAS旧校舎や門入集落へのリサーチ、荒川修作に関する調査、さらに2024年10月に訪問した磯崎新による奈義町美術館（「建築と作品が一体化した公共建築」）と養老天命反転地の比較を関連付け、「エッジ」の視点から考察を行います。ゲストとして東京藝術大学メディア映像M1の坂根大悟さんをお迎えし、彼の専門である鉄道史の視点から大垣と箱物について話題提供をいただきます。午後には自転車に乗って実際に養老へ向かい、養老天命反転地を訪問しつつ、センタービルが街の外れから見える境界（エッジ）を探ります。",
        "student1": "Shota Shimura",
        "student2": "",
        "student3": "",
        "participant1_name": "坂根大悟",
        "participant1_status": "",
        "participant1_profile": "1995年旧大宮市出身。学習院大学文学部史学科卒業。東京藝術大学映像研究科メディア映像専攻修士１年。その土地の持つ歴史や都市を題材に、相反するものが共存しながら、複数の可能性が同時存在する「陰陽太極図的メディア空間」を探求しつつ、立体、映像、中間媒介物を組み合わせ、作品を制作。主な展示歴に2023 年さいたま国際芸術祭公募作品展、2022年六本木アートナイト・オープンコールプロジェクトなど。",
        "participant2_name": "赤松正行",
        "participant2_status": "",
        "participant2_profile": "1961年兵庫県生まれ。メディア作家。京都市立芸術大学大学院美術研究科修了、 博士（美術）。インタラクティブな音楽や映像作品を制作、近年はモビリティとリアリティをテーマにテクノロジーが人と社会へ及ぼす影響を制作を通して考察している。代表作は書籍「Maxの教科書」、「iOSの教科書」、アプリ「Spatial Poetry」、「セカイカメラ（頓智ドット）」、インスタレーション「ウロボロスのトーチ」 など。",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "IAMAS JUNCTION",
        "exhibitors": "對中・カワイ・猪崎",
        "day": "Saturday",
        "time": "12:00-",
        "content": "梶原岐阜県知事時代の箱物行政政策によって誕生したセンタービルをはじめとする建築群と、運動体設計プロジェクト内で昨年実施したIAMAS旧校舎や門入集落へのリサーチ、荒川修作に関する調査、さらに2024年10月に訪問した磯崎新による奈義町美術館（「建築と作品が一体化した公共建築」）と養老天命反転地の比較を関連付け、「エッジ」の視点から考察を行います。ゲストとして東京藝術大学メディア映像M1の坂根大悟さんをお迎えし、彼の専門である鉄道史の視点から大垣と箱物について話題提供をいただきます。午後には自転車に乗って実際に養老へ向かい、養老天命反転地を訪問しつつ、センタービルが街の外れから見える境界（エッジ）を探ります。",
        "student1": "Masaru Tainaka",
        "student2": "KAWAI Takeshi",
        "student3": "Kosei Izaki",
        "participant1_name": "",
        "participant1_status": "",
        "participant1_profile": "",
        "participant2_name": "",
        "participant2_status": "",
        "participant2_profile": "",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "",
        "exhibitors": "",
        "day": "Saturday",
        "time": "13:00-",
        "content": "",
        "student1": "",
        "student2": "",
        "student3": "",
        "participant1_name": "",
        "participant1_status": "",
        "participant1_profile": "",
        "participant2_name": "",
        "participant2_status": "",
        "participant2_profile": "",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "ジェンダーじゃない話をしよう！",
        "exhibitors": "菅実花、松井茂、小林、早田、髙岸(ファシリテーター)",
        "day": "Saturday",
        "time": "14:00-16:00",
        "content": "これまでIAMASでジェンダーに関する議論はあまり行われてきませんでした。男性名詞や女性名詞がある言語って、どんなふうに世界を捉えているのかな？男らしさ・女らしさの意識に影響するのかな？そんな疑問から出発した勉強会の特別編として、IAMASでジェンダーの議論をすることについて考えます。",
        "student1": "",
        "student2": "",
        "student3": "",
        "participant1_name": "菅実花\n\n\n\n",
        "participant1_status": "美術作家",
        "participant1_profile": "情報科学芸術大学院大学准教授および京都芸術大学大学院(通信教育)写真映像領域特任准教授。大衆的な写真文化と、人形の文脈を交錯させた写真・映像作品を手がけ「人間と非人間の境界」を問う。共著に2018年『〈妊婦〉アート論』(青弓社)。VOCA展2020奨励賞受賞。",
        "participant2_name": "松井茂",
        "participant2_status": "IAMAS教授",
        "participant2_profile": "著書に『虚像培養芸術論　アートとテレビジョンの想像力』（フィルムアート社、2021年）。川崎弘二との共著書に『坂本龍一のメディア・パフォーマンス　マス・メディアの中の芸術家像』（同、2023年）。伊村靖子との共編著に『虚像の時代　東野芳明美術批評選』（河出書房新社、2013年）。",
        "participant3_name": "小林史佳",
        "participant3_status": "修士1年",
        "participant3_profile": "餅の形は四角い切り餅、それをトースターで焼いて砂糖醤油をつけて食べる家庭で育つ。一人暮らしを始めてからはトースターを置く場所がないため、水の入った容器に餅を入れて電子レンジで温める。それを汁に入れてお雑煮のようにして食べている。季節は問わない。",
        "participant4_name": "早田仁知",
        "participant4_status": "修士1年",
        "participant4_profile": "IAMAS(M1)所属。2001年生まれ。東京外大言語文化学部ヒンディー語専攻卒業。学部時代には音声学を専門にし、日本語とヒンディー語のオノマトペ対照をテーマに研究。多言語社会であるインド・デリー大学への交換留学を経て、現在は言語の消滅・忘却に関する研究と制作に取り組む。学外では作詞作曲家として楽曲制作等の活動も行っている。",
        "participant5_name": "高岸航平",
        "participant5_status": "修士1年",
        "participant5_profile": "IAMAS(M1)所属。学部の専門は漆工と木工。成層圏で漆造形作品を撮影する「宙漆プロジェクト」代表。現在は生成AIを通した芸術教育について研究に取り組む",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "IAMAS JUNCTION",
        "exhibitors": "山口・ジユン・菊田",
        "day": "Saturday",
        "time": "16:00-",
        "content": "IAMASで扱われている研究分野は多様であるゆえに、学生間でも他の人の研究は知っているようで知らないものです。異なる目的地へ向かう者が行き交いながらも合流する交通の要所「JUNCTION」のように、修士二年生の出展者同士が談話を通して互いの研究テーマについて話し合うIAMAS JUNCTIONを開催します。",
        "student1": "Yuiko Yamaguchi",
        "student2": "JUNG Jieyun",
        "student3": "Yoshie Kikuta",
        "participant1_name": "",
        "participant1_status": "",
        "participant1_profile": "",
        "participant2_name": "",
        "participant2_status": "",
        "participant2_profile": "",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "",
        "exhibitors": "",
        "day": "Saturday",
        "time": "17:00-",
        "content": "",
        "student1": "",
        "student2": "",
        "student3": "",
        "participant1_name": "",
        "participant1_status": "",
        "participant1_profile": "",
        "participant2_name": "",
        "participant2_status": "",
        "participant2_profile": "",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "NxPC.Live vol.72 唵楽と影像",
        "exhibitors": "",
        "day": "Saturday",
        "time": "18:00-",
        "content": "NxPC.Labは、クラブやライブにおけるアーティストと観客の相互作用によってもたらされる場の臨場感を拡大し、ネットへも拡散させるためのメディアテクノロジーの実現を目指した研究機関です。",
        "student1": "",
        "student2": "",
        "student3": "",
        "participant1_name": "Record Prayer",
        "participant1_status": "",
        "participant1_profile": "PhoneTacte という自作楽器を演奏する。指先と足先の繊細な動きで、音と身体が融合する新感覚演奏。",
        "participant2_name": "ニチウシオーハシ",
        "participant2_status": "",
        "participant2_profile": "二人に見えて三人である。とある世界認識方法と景色分解能について。",
        "participant3_name": "Nomad Sentinel",
        "participant3_status": "",
        "participant3_profile": "Nomad Sentinel was born from a series of visual creation experiments and has gradually expanded into installation art, VR art, and interactive art.",
        "participant4_name": "hrx",
        "participant4_status": "",
        "participant4_profile": "乱数発生器は観客に反応するのか？乱数発生器が観客の情動に反応するというアイデアを実証するための実験的パフォーマンス",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "クリティカルサイクリング　ー寒中ライドー",
        "exhibitors": "クリティカル・サイクリング",
        "day": "Sunday",
        "time": "8:00-10:30",
        "content": "来る2月22日にクリティカル・サイクリングと運動体設計の共催による早朝耐寒ライドを行います。これはIAMASの卒展イベントとして行われ、どなたでもご参加いただけます。今年度はIAMAS周辺のゴミを拾いながらサイクリングをします。",
        "student1": "",
        "student2": "",
        "student3": "",
        "participant1_name": "クリティカル・サイクリング",
        "participant1_status": "",
        "participant1_profile": "クリティカル・サイクリング（Critical Cycling）は、サイクリングを楽しみ、その批評性を探求する任意グループです。岐阜県大垣市にあるIAMAS（情報科学芸術大学院大学）を中心に2016年4月より活動をしています。",
        "participant2_name": "",
        "participant2_status": "",
        "participant2_profile": "",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "",
        "exhibitors": "",
        "day": "Sunday",
        "time": "11:00-12:00",
        "content": "",
        "student1": "",
        "student2": "",
        "student3": "",
        "participant1_name": "",
        "participant1_status": "",
        "participant1_profile": "",
        "participant2_name": "",
        "participant2_status": "",
        "participant2_profile": "",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "IAMAS JUNCTION",
        "exhibitors": "橋本・上田",
        "day": "Sunday",
        "time": "12:00-",
        "content": "来る2月22日にクリティカル・サイクリングと運動体設計の共催による早朝耐寒ライドを行います。これはIAMASの卒展イベントとして行われ、どなたでもご参加いただけます。今年度はIAMAS周辺のゴミを拾いながらサイクリングをします。",
        "student1": "Masataka Hashimoto",
        "student2": "Rintaro UEDA",
        "student3": "",
        "participant1_name": "",
        "participant1_status": "",
        "participant1_profile": "",
        "participant2_name": "",
        "participant2_status": "",
        "participant2_profile": "",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "",
        "exhibitors": "",
        "day": "Sunday",
        "time": "13:00-",
        "content": "",
        "student1": "",
        "student2": "",
        "student3": "",
        "participant1_name": "",
        "participant1_status": "",
        "participant1_profile": "",
        "participant2_name": "",
        "participant2_status": "",
        "participant2_profile": "",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "ポスト記述言語学：言語の新しい保存方法を探る",
        "exhibitors": "早田仁知・伊藤雄馬・マユンキキ・髙岸航平",
        "day": "Sunday",
        "time": "14:00-16:00",
        "content": "このイベントは、言語学とアートの交差点での創造性と表現を探求します。言語学と様々な形態\nのアートの融合から生まれる新たな可能性を探ります。この対話を通じて、参加者が異なる分野\nの境界を超えた創造的アイデアを育成し、それを実践的な応用へと繋げる橋渡しの役割を果た\nすことを目的としています。\n\n",
        "student1": "",
        "student2": "",
        "student3": "",
        "participant1_name": "伊藤雄馬\n\n\n",
        "participant1_status": "言語学者",
        "participant1_profile": "1986年生。タイ・ラオスで話されるムラブリ語を中心にフィールドワークを行う。大学教員を経て、2020年から独立。ムラブリ語が母語の次に得意。2022年公開のドキュメンタリー映画『森のムラブリ』(監督:金子遊)に出演し、現地コーディネーター、字幕翻訳を担当。著書に『ムラブリ　文字も暦も持たない狩猟採集民から言語学者が教わったこと』（集英社インターナショナル）、『人類学者と言語学者が森に入って考えたこと』（教育評論社、共著）など。",
        "participant2_name": "マユンキキ",
        "participant2_status": "",
        "participant2_profile": "1982年北海道生まれ。アイヌの伝統歌を歌う「マレウレウ」「アペトゥンペ」のメンバー。2021年よりソロ活動開始。2018年より、自身のルーツと美意識に纏わる興味・関心からアイヌ女性の伝統的な文身「シヌイェ」の研究を開始。現代におけるアイヌの存在を、あくまで個人としての観点から探求し、表現している。",
        "participant3_name": "早田仁知",
        "participant3_status": "修士1年",
        "participant3_profile": "IAMAS(M1)所属。2001年生まれ。東京外大言語文化学部ヒンディー語専攻卒業。学部時代には音声学を専門にし、日本語とヒンディー語のオノマトペ対照をテーマに研究。多言語社会であるインド・デリー大学への交換留学を経て、現在は言語の消滅・忘却に関する研究と制作に取り組む。学外では作詞作曲家として楽曲制作等の活動も行っている。",
        "participant4_name": "高岸航平",
        "participant4_status": "修士1年",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "技術/手法の実験の積み重ねから生まれる視覚表現を紐解く",
        "exhibitors": "成瀬陽太・橋本麦・石川将也",
        "day": "Sunday",
        "time": "16:00-18:00",
        "content": "バイオロジカルモーションと呼ばれる映像・アニメーションではよく用いられる技法、表現を転用した作品を制作した成瀬陽太と、映像装置のワークショップにてバイオロジカルモーションや錯視などの認知科学的な要素を取り込み制作を行う石川将也、ツールを自ら作ることから新たな映像表現を模索する橋本麦とで映像装置・ツールから映像表現を開拓することについて語る。\n実際に制作した作品やその過程と、過去の映像装置・ツールの歴史との関連性、そして他にも気になる技法やハックしがいのある事象などを議論したい。",
        "student1": "Sanata NARUSE",
        "student2": "",
        "student3": "",
        "participant1_name": "橋本麦\n\n",
        "participant1_status": "映像作家、ツール開発者",
        "participant1_profile": "実験映像やハッカー文化に影響を受け、CGIからコマ撮りアニメーション、ミュージック・ビデオ、インタラクティブ作品まで、多岐に渡って個人で制作を続けてきた。さまざまな表現手法の実験の積み重ねにより、多様な視覚表象のスタイルを模索している。",
        "participant2_name": "石川将也",
        "participant2_status": "グラフィックデザイナー / 研究者",
        "participant2_profile": "1980年生まれ。慶應義塾大学大学院 政策・メディア研究科 修了。佐藤雅彦研究室を経て、2019年までクリエイティブグループ「ユーフラテス」に所属。20年独立。視覚表現の開発と、視覚認知の研究を基点に、グラフィックデザイン、映像、インスタレーション、科学玩具とそれを用いたワークショップの開発など、さまざま活動している。代表作に「factory of dream」「そうとしかみえない」「歩くの歌」（Eテレ2355 / 0655）「ねじねじの歌」「クッキー型の型の歌」（ピタゴラスイッチ）、「Layers Act」「光のレイヤー」「マグネタクトアニマル」「四角が行く」「開け箱」など。2024年より U-NEXT Kids オリジナルコンテンツ「ねむるま えほん」「うご工作」の監督として企画の立案から携わっている。",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "レセプション",
        "exhibitors": "",
        "day": "Sunday",
        "time": "18:00-",
        "content": "",
        "student1": "",
        "student2": "",
        "student3": "",
        "participant1_name": "",
        "participant1_status": "",
        "participant1_profile": "",
        "participant2_name": "",
        "participant2_status": "",
        "participant2_profile": "",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "",
        "exhibitors": "",
        "day": "Monday",
        "time": "10:00-12:00",
        "content": "",
        "student1": "",
        "student2": "",
        "student3": "",
        "participant1_name": "",
        "participant1_status": "",
        "participant1_profile": "",
        "participant2_name": "",
        "participant2_status": "",
        "participant2_profile": "",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "",
        "exhibitors": "",
        "day": "Monday",
        "time": "12:00-",
        "content": "",
        "student1": "",
        "student2": "",
        "student3": "",
        "participant1_name": "",
        "participant1_status": "",
        "participant1_profile": "",
        "participant2_name": "",
        "participant2_status": "",
        "participant2_profile": "",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "",
        "exhibitors": "",
        "day": "Monday",
        "time": "13:00-",
        "content": "",
        "student1": "",
        "student2": "",
        "student3": "",
        "participant1_name": "",
        "participant1_status": "",
        "participant1_profile": "",
        "participant2_name": "",
        "participant2_status": "",
        "participant2_profile": "",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "",
        "exhibitors": "",
        "day": "Monday",
        "time": "16:00-18:00",
        "content": "",
        "student1": "",
        "student2": "",
        "student3": "",
        "participant1_name": "",
        "participant1_status": "",
        "participant1_profile": "",
        "participant2_name": "",
        "participant2_status": "",
        "participant2_profile": "",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    },
    {
        "eventName": "IAMASONIC 2025 - pit in",
        "exhibitors": "",
        "day": "Monday",
        "time": "18:00-",
        "content": "IAMASONICとは実験的な音楽イベントです。人生のサービスエリアと呼ばれるIAMASで開催される本イベントは、旅路での給油や修理を行うピットエリアのように、「苦悩と誠実」の日々を送るIAMAS生、特に旅立ちを控えたM2の学生たちのリセット、そして開かれた自己表現の場として機能します。屋外開催のため、暖かい服装でご参加ください。",
        "student1": "",
        "student2": "",
        "student3": "",
        "participant1_name": "",
        "participant1_status": "",
        "participant1_profile": "",
        "participant2_name": "",
        "participant2_status": "",
        "participant2_profile": "",
        "participant3_name": "",
        "participant3_status": "",
        "participant3_profile": "",
        "participant4_name": "",
        "participant4_status": "",
        "participant4_profile": "",
        "participant5_name": "",
        "participant5_status": "",
        "participant5_profile": "",
        "participant6_name": "",
        "participant6_status": "",
        "participant6_profile": ""
    }
];