export const MASTER_INFO = [
    {
        "studentId": 21110,
        "authorJapaneseName": "嶋 晏澄",
        "authorEnglishName": "Azumi Shima",
        "profileJapanese": "岐阜生まれ岐阜育ち。",
        "profileEnglish": "Native of Gifu.",
        "X_URL": "",
        "instagram_URL": "",
        "other_URL": "",
        "workTitleJapanese": "Shaderを活用したワークショップを通じた線形代数の各項目に対する意識の変化とShader技術の普及に関する研究",
        "workTitleEnglish": "A Study on Changes in Perception of Each Aspect of Linear Algebra and the Dissemination of Shader\nTechnology through Shader-Based Workshops",
        "workDescriptionJapanese": "プログラミング教育の普及に伴い、プログラミングで線形代数を利用するShaderを活用した3つのワークショップを企画・実施。Shader独自のアプローチやレイマーチングの習得を通じ、参加者の年齢やスキルに応じた三段階の目標設定で継続利用を促進。Shaderの継続利用による線形代数各要素の理解度の変化を計測した。展示では各ワークショップの設計資料や開発したアプリケーションの展示を行う。",
        "workDescriptionEnglish": "In response to the growing popularity of programming education, I designed and implemented workshop programs focusing on Shaders that enable the practical application of linear algebra through programming. We set three distinct learning goals based on varying age groups and skill levels, from understanding Shader-specific concepts to mastering ray marching techniques. We measured changes in participants' understanding of various linear algebra elements through their continued use of Shaders. The exhibition showcases the design documentation from each workshop and displays the developed applications",
        "place1": "センタービル12F",
        "place2": "作業室 C1202"
    },
    {
        "studentId": 21112,
        "authorJapaneseName": "竹本誠",
        "authorEnglishName": "Makoto Takemoto",
        "profileJapanese": "植物が好き",
        "profileEnglish": "I Love Plants !",
        "X_URL": "",
        "instagram_URL": "https://www.instagram.com/maquoto/",
        "other_URL": "",
        "workTitleJapanese": "AR挙式",
        "workTitleEnglish": "AR Ceremony",
        "workDescriptionJapanese": "ARを使った参加型挙式",
        "workDescriptionEnglish": "Interactive weddings with AR",
        "place1": "センタービル 3F",
        "place2": "ギャラリー1 C311"
    },
    {
        "studentId": 21119,
        "authorJapaneseName": "宮﨑那奈子",
        "authorEnglishName": "Nanako Miyazaki",
        "profileJapanese": "岐阜県大垣市出身。学部で劇映画を中心とした映像表現について学んだのち、IAMASで個人による映像作品を制作・研究する。",
        "profileEnglish": "Born in Ogaki, Gifu, Japan.\nIn my undergraduate years I studied visual expression with a focus on fictional films.\nAfterwards, I went on to produce and research individual video works at IAMAS.",
        "X_URL": "",
        "instagram_URL": "",
        "other_URL": "",
        "workTitleJapanese": "Seeing Exercise",
        "workTitleEnglish": "Seeing Exercise",
        "workDescriptionJapanese": "2部構成の短編映像作品。前半は撮影時に気づかなかった映像内の要素にアフレコで言及し、撮影者の主観的な視覚とカメラの客観的な視覚の違いを意識化させた。後半は50秒のモノクロ・サイレント映像で、リュミエール映画を彷彿とさせる視覚世界を提示した。本作は、観賞者の能動的な鑑賞によって新たな視覚体験の発見を促すことを目標に制作した。",
        "workDescriptionEnglish": "This work is a short video piece split into two parts.\nIn the first half of the film, the recording referenced elements in the video that were not noticed during the shooting, making the viewer aware of the difference between the subjective vision of the filmer and the objective vision of the camera.\nThe second half was a 50-second black-and-white silent film that presented a visual world reminiscent of a Lumière film.\nThis work was created with the goal of encouraging the discovery of new visual experiences through active viewing by the viewer.\n",
        "place1": "センタービル 3F",
        "place2": "シアター C314"
    },
    {
        "studentId": 22106,
        "authorJapaneseName": "後藤朋美",
        "authorEnglishName": "Tomomi Goto",
        "profileJapanese": "国内外の旅や滞在を経て作品を制作。「Art meets 07」（アーツ前橋、2022）、「海の森、海のいま展」（青山・スパライルガーデン、2022）、「表現の生態系 」（アーツ前橋、2019年）、「Platinum」（Gallery Trax、2010）。「音の花束 ・20周年関連ワークショップ」（東京都現代美術館、2015）、吉本ばなな氏著書「おとなになるってどんなこと？」日伊の装画・挿画など",
        "profileEnglish": "Through many travels and stays both domestically and abroad she creates works of art. Some exhibitions include “Art meets07” (Arts Maebashi, 2022), “The Forest of the Sea / The Present of the Sea” (Aoyama – Spiral Garden, 2022), “The Ecology of Expression” (Arts Maebashi, 2019), and “Platinum” (Gallery Trax, 2010). Other works are “Bouquet of Sound – 20th Anniversary related workshop” (Museum of Contemporary Art Tokyo, 2015), and the book cover art work and in-book illustrations for Ms.Banana Yoshimoto’s book “What does it mean to become an adult?”",
        "X_URL": "",
        "instagram_URL": "",
        "other_URL": "https://www.tomomigoto.com/tomomi_goto.html",
        "workTitleJapanese": "Trust Thy Scars（あなたの傷を信頼して）",
        "workTitleEnglish": "Trust Thy Scars",
        "workDescriptionJapanese": "氷・土といった変容する物質を用いた本作品は、展示中も刻々と変化し続けます。氷の手が水となり溶けて揮発していくと同時に、水は素焼きの土器に受け止められ、やがて大気へと変化していきます。癒えていく過程のようにも見えるその様相を通して、本質的な治癒とは何かを問い続けます。同時に、自然の一部としての身体が大きな生命の循環の中にあり、地球の諸問題とも深く繋がっていることを示唆しています。",
        "workDescriptionEnglish": "This artwork uses materials such as ice and earth which transform, and whilst being exhibited they continue to change moment by moment. The hands of ice become water, melt, and at the same time as the volatilization the water is caught by the unglazed earthenware. Before long, it transforms into the atmosphere. Through this condition which appears to be like a process of healing, we continue to question what healing is intrinsically. At the same time, it is implied that the body as a part of nature is included in the great cycle of life, and it is deeply connected with many global problems.",
        "place1": "センタービル 4F",
        "place2": "作業室 C415"
    },
    {
        "studentId": 23101,
        "authorJapaneseName": "浅井睦",
        "authorEnglishName": "Mutsushi Asai",
        "profileJapanese": "1991年大阪府生まれ。舞鶴工業高等専門学校機械工学科修了。IAMAS 博士課程前期在学中。日常生活の中から感じることのできる感覚的なことを取り扱い、ハードウェア/映像/体験など形態に囚われない表現方法にて不可視の感覚表現に取り組む。",
        "profileEnglish": "Born in Osaka Prefecture in 1991. Graduated from Maizuru National College of Technology, Department of Mechanical Engineering. Currently enrolled in the master's program at IAMAS. Focuses on exploring sensory experiences derived from everyday life through expressions that transcend specific forms, such as hardware, video, and experiential installations, aiming to represent invisible sensations.",
        "X_URL": "https://x.com/NativePlastic",
        "instagram_URL": "https://www.instagram.com/mutsushiasai/",
        "other_URL": "https://scrapbox.io/metalium/",
        "workTitleJapanese": "Superposition machine/Vibes watcher",
        "workTitleEnglish": "Superposition machine/Vibes watcher",
        "workDescriptionJapanese": "Superposition machine は、音と形が出力される多人数参加型ヴィジュアルシンセサイザーです。本装置を複数人で操作すると無目的であるにも関わらず発生する一体感のような感覚がグループに発生し、この現象をVibesと定義しました。Vibes現象を観測するための観測装置Vibes Watcherはリアルタイムに感覚の測定を通じて現象の観察を行うことができます。",
        "workDescriptionEnglish": "Superposition Machine is a multi-user visual synthesizer that outputs sound and form. When operated by multiple participants, it generates a shared sense of unity despite lacking a clear purpose. This phenomenon is defined as \"Vibes.\" To observe this phenomenon, the Vibes Watcher, a device designed for real-time sensory measurement, enables the observation and analysis of these occurrences.",
        "place1": "センタービル12F",
        "place2": "作業室 C1202"
    },
    {
        "studentId": 23103,
        "authorJapaneseName": "猪﨑康世",
        "authorEnglishName": "Kosei Izaki",
        "profileJapanese": "2000年、宮崎県生まれ。",
        "profileEnglish": "Born in Miyazaki in 2000.",
        "X_URL": "",
        "instagram_URL": "",
        "other_URL": "https://izakikosei.com/",
        "workTitleJapanese": "虫・あなたのチューブ",
        "workTitleEnglish": "mushi / your tube",
        "workDescriptionJapanese": "『虫・あなたのチューブ』は、複数のタッチディスプレイとそれらを接続するチューブ、接触する鑑賞者の身体の間を移動する「虫」から構成されている。「虫」は、文字として表現されながら、その在り処を変えていく。「虫」はタッチディスプレイに接触した指の下で文字としての形を失うことで、触れた身体の中に「虫」が移ることを想像させる。また、接触した指の下に文字が出現することでタッチディスプレイに「虫」が移ることを想像させる。作品によって、「虫」の在り処としての身体、「虫」が出入する通路としての身体を見出していく。",
        "workDescriptionEnglish": "\"mushi / your tube\" consists of multiple touch displays with tubes connecting them, and \"mushi\" that move between the bodies of viewers who come into contact with them. The \"mushi\" changes its whereabouts while being expressed as text. The \"mushi\" loses its form as text beneath the finger that touches the touch display, leading one to imagine that the \"mushi\" moves into the body it touches. Additionally, the appearance of text under the finger on contact leads one to imagine that the \"mushi\" moves out onto the touch display. Through this work, the whereabouts of the \"mushi\" and it's passage for entry and exit as a body are discovered.",
        "place1": "センタービル 3F",
        "place2": "ギャラリー1 C311"
    },
    {
        "studentId": 23104,
        "authorJapaneseName": "上田麟太朗",
        "authorEnglishName": "Rintaro UEDA",
        "profileJapanese": "茨城県龍ケ崎市出身。",
        "profileEnglish": "Born in Ryugasaki City, Ibaraki Prefecture",
        "X_URL": "",
        "instagram_URL": "",
        "other_URL": "",
        "workTitleJapanese": "視聴者の部屋",
        "workTitleEnglish": "Viewers' room",
        "workDescriptionJapanese": "ライブ配信のコミュニケーションは対面のそれと違うようで似ている。\n実際に顔を合わせる訳ではないのに人はコミュニケーションをとる。\n思い出話をするように、噂話をするように、画面の向こうを知りたがる。\nコメント欄は部屋のようだ。\nこの部屋にはたくさんの人間が言葉を発したり、リアクションをとったりする。\nもちろん身体はないのだが。そして配信が終われば、皆出ていく。",
        "workDescriptionEnglish": "Live streaming communication is and similar to face-to-face communication.\nPeople communicate even though they don't actually meet face to face.\nThey want to know what's on the other side of the screen, like talking about memories or gossiping.\nThe comment section is like a room.\nThere are many people in this room speaking and reacting.\nOf course they don't have a body. And once the broadcast is over, everyone leaves.",
        "place1": "センタービル 2F",
        "place2": "男子仮眠室 C211"
    },
    {
        "studentId": 23105,
        "authorJapaneseName": "璃月ゆあ",
        "authorEnglishName": "Yua Riduki",
        "profileJapanese": "2000年愛知県生まれ。京都産業大学情報理工学部卒。大学にてソフトウェア工学やプログラミング言語学などを学んだ後、IAMASへ。情報工学だけではなく様々な活動に取り組む。代表作「月の声を聴くための言葉」(2022)",
        "profileEnglish": "Born in Aichi Prefecture, in 2000. Graduated from the Faculty of Information Science and Engineering at Kyoto Sangyo University. After studying software engineering, programming language theory, and other subjects at university, pursued higher education at IAMAS (Institute of Advanced Media Arts and Sciences). Engaged in a wide range of activities beyond just information engineering. Major work: 月の声を聴くための言葉(tuki no kowe wo kiku tame no kotonoha) (2022).",
        "X_URL": "https://x.com/yuntexya_riduki",
        "instagram_URL": "",
        "other_URL": "",
        "workTitleJapanese": "同業社コミュニティの形成と印刷産業発展の可能性について\n- インタビュー分析による他己紹介をワークショップの契機として -",
        "workTitleEnglish": "Regarding the formation of peer company communities and the possibility of development in the printing industry\n- Using Introduction of the company through interview analysis as a catalyst for the workshop -",
        "workDescriptionJapanese": "印刷産業に携わる中小企業に焦点を当て、印刷産業が活性化するための企業連携の可能性について考察する。複数の印刷会社経営者へのインタビューをもとにワークショップを構成。複数の企業の経営者が参加するワークショップを用いてコミュニティの形成を試みる。これは印刷業界に提言する新たな取り組みである。",
        "workDescriptionEnglish": "Focusing on small and medium-sized enterprises in the printing industry, this study explores the potential for business collaboration to revitalize the sector. Based on interviews with multiple printing company executives, a workshop was designed to foster discussions. By bringing together executives from various companies, the workshop aims to build a community. This represents a novel initiative offering recommendations to the printing industry.",
        "place1": "センタービル12F",
        "place2": "作業室 C1202"
    },
    {
        "studentId": 23106,
        "authorJapaneseName": "カワイタケシ",
        "authorEnglishName": "KAWAI Takeshi",
        "profileJapanese": "「わかりあえなさ」をテーマとして、映像やパフォーマンスを用いた作品を制作。",
        "profileEnglish": "He creates works of art using video and performances based on the theme of “The absurdity of not understanding (you).”",
        "X_URL": "https://x.com/kawai_takec",
        "instagram_URL": "https://www.instagram.com/kawai_takec/",
        "other_URL": "https://x.gd/kawai_takec",
        "workTitleJapanese": "息をしている(Breathing with (you).)",
        "workTitleEnglish": "Breathing with (you).",
        "workDescriptionJapanese": "「わかりあえなさ」という不条理を、可能性として捉え直すための実践。",
        "workDescriptionEnglish": "A work to recapture the absurdity of “I can't understand (you).” as a possibility.",
        "place1": "センタービル 3F",
        "place2": " ビジュアルスタジオ C305"
    },
    {
        "studentId": 23107,
        "authorJapaneseName": "菊田佳恵",
        "authorEnglishName": "Yoshie Kikuta",
        "profileJapanese": "川崎生まれ。学部時代に数理科学科にてコミュニケーションロボットの楽曲リコメンドシステムについて研究後、就職。IAMAS入学後は人の心の動きに着目し、人とロボットの共生する未来を思い描いている。",
        "profileEnglish": "Born in Kawasaki City. During her undergraduate years in the Department of Mathematics, she researched a music recommendation system for communication robots, then got a job. After enrolling at IAMAS, she focused on the movements of the human heart and envisioned a future where humans and robots coexist.",
        "X_URL": "https://x.com/wagahaiha_kikuy?t=wcVSl4lnS0kMgiKfuDk1Lw&s=09",
        "instagram_URL": "",
        "other_URL": "",
        "workTitleJapanese": "私のネイルが私のネイルになるまで",
        "workTitleEnglish": "Until my nails become my nails.",
        "workDescriptionJapanese": "本作品は、「あるテーマに基づき自身で納得のいくネイルをデザインした後、他者と会話を行い、もう一度同じテーマでネイルをデザインする。」という手法を繰り返し行った作品群です。今回は16テーマ分の会話前のネイル・会話の内容(音声と文字起こし)・会話後のネイルを展示します。\n自己が他者と触れ合い、干渉することで変容していく心情や思想の道のりを、他者との会話とネイルデザインの変化を用いて表現していきます。",
        "workDescriptionEnglish": "This work is a group of works that repeatedly employs the technique of \"designing nails that I'm satisfied with based on a certain theme, then talking to someone else, and then designing nails again on the same theme.\" This time, for 16 themes, the nails before the conversation, the conversation (audio and transcript), and the nails after the conversation will be exhibited.\nThe journey of emotions and thoughts is expressed through the conversations with somebody and the changes in nail design.",
        "place1": "センタービル 3F",
        "place2": "ギャラリー1 C311"
    },
    {
        "studentId": 23109,
        "authorJapaneseName": "三波蒼菜",
        "authorEnglishName": "aona minami",
        "profileJapanese": "プロダクトデザインを学んだのちIAMAS入学。身体的不器用さと座ることをテーマに「できるようになる」ということについての研究を行っている。",
        "profileEnglish": "After studying product design, I joined at IAMAS. My research focuses on the theme of \"being able to do it,\" under the theme of physical clumsiness and sitting.",
        "X_URL": "https://x.com/aona_minami",
        "instagram_URL": "https://www.instagram.com/aona_minami/",
        "other_URL": "",
        "workTitleJapanese": "身体的不器用さのある子どものための、着座姿勢をサポートするプロダクトについての研究\nー身体的な不器用さが要因で食事が取りづらくなっている生徒の事例を通してー",
        "workTitleEnglish": "Research on posture support products for children with coordination difficulties. - Through the case study of a student who has difficulty eating due to coordination difficulties. –",
        "workDescriptionJapanese": "身体的不器用さがある子どもは、椅子に座って学習や食事等の作業をする際に姿勢を保つことが難しい場合があります。本研究では一人の生徒との実践を通して、デジタルファブリケーション機器を用いて製作した給食時の姿勢を補助する椅子を提案しました。姿勢を保つための筋力の向上や食事量の増加などの効果を期待し、生徒本人が生活しやすくなることを目指しています。",
        "workDescriptionEnglish": "Children with physical clumsiness may have difficulty maintaining posture when sitting in a chair to learn, eat, or perform other tasks. Through practice with one student, this study proposed a chair that assists with posture during mealtime, which was fabricated using digital fabrication equipment. I expect the chair to improve muscle strength for maintaining posture and increase the amount of food eaten, thereby making life easier for the student him/herself.",
        "place1": "センタービル12F",
        "place2": "作業室 C1202"
    },
    {
        "studentId": 23110,
        "authorJapaneseName": "志村翔太",
        "authorEnglishName": "Shota Shimura",
        "profileJapanese": "神奈川県川崎市出身。世界旅行、事業開発を経てIAMAS博士前期課程に在籍。松尾芭蕉が『奥の細道』の結びの地とした岐阜県大垣市への引越しをきっかけに「モビル文学」シリーズの作品制作を開始する。",
        "profileEnglish": "Born in Kawasaki City, Kanagawa Prefecture. After traveling the world and engaging in business development, enrolled in the master's program at IAMAS. Inspired by a move to Ogaki City, Gifu Prefecture, the concluding location of Matsuo Basho's The Narrow Road to the Deep North, began creating works in the \"Mobile Literature\" series.",
        "X_URL": "https://x.com/shotashimura",
        "instagram_URL": "https://www.instagram.com/shotashimura0816/",
        "other_URL": "",
        "workTitleJapanese": "モビル文学",
        "workTitleEnglish": "Mobile Literature",
        "workDescriptionJapanese": "「モビル文学」は自転車を使った移動並びにモバイルテクノロジーを文学表現と融合させることを目指し、自転車と装置を用いて各街をテーマにした小説をキャンバスとしての都市に描き出す連作です。",
        "workDescriptionEnglish": "\"Mobile Literature\" is a series of works that aim to fuse mobility using bicycles and mobile technology with literary expression. Using bicycles and devices, it portrays novels themed around various cities, painting them onto the urban canvas.",
        "place1": "センタービル 4F",
        "place2": "講義室2 C414"
    },
    {
        "studentId": 23111,
        "authorJapaneseName": "ジョン ジユン",
        "authorEnglishName": "JUNG Jieyun",
        "profileJapanese": "2000年韓国生まれ、2019年より日本で生活をしている。\n多摩美術大学情報デザイン学科情報デザインコース卒業後 IAMASへ。\n多言語話者である自分の経験から感じたコミュニケーション体験をもとに、表現している。",
        "profileEnglish": "Born 2000 in South Korea, living in Japan since 2019.\nGraduated from Tama Art University, Department of Information Design, Interaction Design Course, and entered IAMAS.\nShe expresses herself based on her communication experiences as a polyglot.",
        "X_URL": "https://x.com/cobaltinnv",
        "instagram_URL": "https://www.instagram.com/cobaltinnv",
        "other_URL": "https://cobaltinnv.com",
        "workTitleJapanese": "ただよう - drift",
        "workTitleEnglish": "drift",
        "workDescriptionJapanese": "「ただよう」とは、ゆらゆらとさまようさま。ある雰囲気やけはいが、静かにその場に満ちていくさま。\n何となく感じられ、はっきりとは掴めないけれど、確かに存在していること。\nこの不安定さや落ち着きのなさ、そして、特定の形や目的を持たずに漂う感覚。\n\n羊の頭を被り、川に浸かりながら自作の文章を朗読する。\nパフォーマンスはライブ配信形式で行い、観客はその様子を鑑賞する。\n言葉が消える中で、コミュニケーションの限界や他者との理解の不確実さに向き合おう。",
        "workDescriptionEnglish": "\"ただよう - drift\" refers to swaying gently, wandering without a clear direction. It is the way an atmosphere or aura quietly fills a space. Something that is faintly perceptible, elusive yet undeniably present. This instability, this unease—an unanchored sense of floating without a defined shape or purpose.\n\nWearing a sheep’s head, immersed in a river, reading aloud one’s own words.  \nThe performance unfolds as a live stream, where the audience witnesses the scene.  \nAs words dissolve into silence, we confront the limits of communication and the uncertainty of understanding others.  ",
        "place1": "センタービル 3F",
        "place2": "ギャラリー3 C313"
    },
    {
        "studentId": 23113,
        "authorJapaneseName": "對中優",
        "authorEnglishName": "Masaru Tainaka",
        "profileJapanese": "アーティスト、VJ、DJ",
        "profileEnglish": "Artist,VJ,DJ",
        "X_URL": "https://x.com/msr_tainaka",
        "instagram_URL": "https://www.instagram.com/msr_tainaka/",
        "other_URL": "https://scrapbox.io/msrtainaka/",
        "workTitleJapanese": "Drifting",
        "workTitleEnglish": "Drifting",
        "workDescriptionJapanese": "私たちがゲームをしている時、身体は二つの空間に存在し、意識は二つの空間を漂うように行き来する。こういった空間の二重性に着目し、バーチャルな空間と現実空間の双方をパファーマンスとインターネット的 (SNS、VRSNS、オンラインゲーム ) な通信のメタファー（壁と紙飛行機）を活用して展示空間に切り出す。",
        "workDescriptionEnglish": "When we play games, our bodies exist in two spaces, and our consciousness drifts back and forth between the two. Focusing on the duality of these spaces, the exhibition space utilizes the metaphors of performance and Internet-like communication (SNS, VRSNS, online games) to create both virtual and real spaces (walls and paper airplanes).",
        "place1": "センタービル 4F",
        "place2": "ホール C404"
    },
    {
        "studentId": 23114,
        "authorJapaneseName": "徳保晴人",
        "authorEnglishName": "Tokubo Haruto",
        "profileJapanese": "2000年愛知県名古屋市生まれ。多摩美術大学情報デザイン学科を卒業後にIAMAS入学。収集する癖があり、バグるという現象を表現とするため制作をおこなっている。映像やグラフィックなどデザインをする。",
        "profileEnglish": "\"Born in Nagoya, Aichi, Japan in 2000. Entered IAMAS after graduating from the Department of Information Design, Tama Art University. He has a habit of collecting bugs. He creates his works in order to express the phenomenon of bugs. He works with video and graphic design.\"",
        "X_URL": "https://x.com/harutotogaku",
        "instagram_URL": "https://www.instagram.com/harutotogaku/",
        "other_URL": "",
        "workTitleJapanese": "自動ドア - 白紙のタイプ",
        "workTitleEnglish": "Automatic door - White paper type",
        "workDescriptionJapanese": "これは、自動ドアにA4サイズの白紙を貼ることでセンサーの誤作動を意図的に誘発し、バグの現象を再解釈する試みである。偶然に観察したバグを再現していく中で、技術的エラーが持つ滑稽さや偶発性の中に、社会との対話を生み出した。単なる不具合として排除されがちなバグが、装置の構造や社会的文脈との関係性の中でいかに意味を持つかを探求する。公共空間での実践を通じて制作された映像は、見過ごされる現象がいかに新たな視点をもたらすかを問うものである。",
        "workDescriptionEnglish": "This was an attempt to reinterpret the phenomenon of bugs by intentionally inducing sensor malfunctions by placing A4-sized blank sheets of paper on automatic doors. In reproducing bugs observed by chance, the project created a dialogue with society in the ridiculousness and contingency of technical errors. The work explores how bugs, which are often dismissed as mere glitches, take on meaning in relation to the structure of the device and its social context. The video, produced through practice in public spaces, questions how overlooked phenomena can bring about new perspectives.",
        "place1": "センタービル 3F",
        "place2": "ギャラリー2 C312"
    },
    {
        "studentId": 23115,
        "authorJapaneseName": "成瀬陽太",
        "authorEnglishName": "Santa NARUSE",
        "profileJapanese": "大阪出身、長野育ち。慶應義塾大学環境情報学部を卒業後にIAMASに入学。\n「探索的行為が伴うインタラクティブな鑑賞体験から現実空間の見え方、見る意識を変えること」をテーマに領域横断的な研究・作品制作を行っている。",
        "profileEnglish": "Born in Osaka in 2000 and raised in Nagano. After graduating from Keio University (SFC), he entered the Institute of Advanced Media Arts and Sciences (IAMAS) in 2023. His interdisciplinary research and creative work focuses on 'changing the perception and awareness of real space through interactive viewing experiences accompanied by exploratory actions.\n",
        "X_URL": "https://twitter.com/_s4nt4",
        "instagram_URL": "https://www.instagram.com/__s4nt4/",
        "other_URL": "https://scrapbox.io/s4nt4-cc/",
        "workTitleJapanese": "Sight / Insight",
        "workTitleEnglish": "Sight / Insight",
        "workDescriptionJapanese": "Sight / Insightは、人間の、光を見る意識の変容を試みるインタラクティブ・インスタレーション作品である。 \n暗い部屋に入ると、複数の小さなLEDの光点が動いている。光点に近づいたり遠ざかったり探索しながら観察してみると、光の集合から「何か」が見えてくる。\n光の観察を経て実空間に戻ると、夜の路上を見るときに「何か」を見ようと探索するように意識が変容しているかもしれない。",
        "workDescriptionEnglish": "*Sight / Insight* is an interactive installation that seeks to transform the way humans perceive light.\n\nWhen you enter a dark room, you see multiple small LED lights moving about. As you approach and retreat from these points of light—actively exploring while observing—something begins to emerge from the cluster.\n\nAfter experiencing this act of observing light, when you return to ordinary space, you may find that your awareness has shifted. Looking at the streets at night, you might now find yourself searching for that elusive “something.”",
        "place1": "センタービル 3F",
        "place2": "サウンドスタジオ前廊下 C302   "
    },
    {
        "studentId": 23116,
        "authorJapaneseName": "バク ソミン",
        "authorEnglishName": "BAK Somin",
        "profileJapanese": "インスタレーションを中心に写真、映像、彫刻、絵画などの幅広い手法から作品を作っている。恐怖や恥など二分できない感情について言葉ではない表現を行う。\n",
        "profileEnglish": "Creating art through a diverse array of techniques, primarily installations, alongside photos, videos, sculptures, and paintings. Exploring non-verbal expressions of complex emotions, particularly fear and shame.",
        "X_URL": "",
        "instagram_URL": "https://www.instagram.com/s0_null?igsh=Y2xuaHZyNTRtYjU4",
        "other_URL": "",
        "workTitleJapanese": "恥を知る滅び方について",
        "workTitleEnglish": "For the Shame on the Destruction",
        "workDescriptionJapanese": "「恥を知る滅び方について」という言葉を基に、現代の恥について考えた3つの作品を同じ空間に展示し連続的に観られるようにした。各作品は絵画、映像を使用した彫刻、体験型インスタレーションなどそれぞれ違う形をしている。作者の恥についての考えを作品という形で連続的に鑑賞することから、鑑賞者に作家の考察に触れ現代の恥について考えられる呪術的な空間を構成した。",
        "workDescriptionEnglish": "Based on the phrase \"For the Shame on the Destruction,\" three artworks exploring the contemporary concept of shame are exhibited in the same space, allowing for a consecutive viewing experience. Each work takes a different form, including a painting, a sculpture using video, and an interactive installation.\nThe artist's reflections on shame unfold continuously through these artworks, creating a shamanic space that invites the viewers to engage with the artist's reflections and reflect on the contemporary understanding of shame.",
        "place1": "センタービル 3F",
        "place2": "ギャラリー2 C312"
    },
    {
        "studentId": 23117,
        "authorJapaneseName": "橋本正隆",
        "authorEnglishName": "Masataka Hashimoto",
        "profileJapanese": "埼玉県生まれ。高等学校情報科教諭。大学卒業後、通信機器メーカーでASIC設計に従事。退職後、青年海外協力隊員（コンピュータ技術）としてタンザニアでの２年間の活動を経て現職。2019年から情報科教育に関する教科書指導書、問題集、副教材の執筆にも携わる。",
        "profileEnglish": "Born in Saitama Prefecture, currently works as a high school informatics teacher. After graduating university, he worked as an ASIC designer at a telecommunications equipment manufacturer. Following his corporate career, he spent two years in Tanzania as a Japan Overseas Cooperation Volunteer (JOCV) specializing in computer technology. Since taking his current position, he has been actively involved in developing educational materials for Education of Information Studies since 2019, including teacher's guides, workbooks, and supplementary materials for textbooks.",
        "X_URL": "",
        "instagram_URL": "",
        "other_URL": "",
        "workTitleJapanese": "生徒の体験に基づくメタ認知と相互理解によるメディアリテラシー教育",
        "workTitleEnglish": "Media Literacy Education through Metacognition and Mutual Understanding Based on Students' Experiences",
        "workDescriptionJapanese": "高等学校におけるメディアリテラシー教育の授業デザインと開発した教材を作品として提示する。メディアリテラシーを「メディアを通して⼈や社会と関わる際の、⾃⾝の評価軸を持つ能力」と捉え、当事者性と包括性を両⽴し社会と接続した授業の実現を志向する。自身のメディア体験の振り返り、クラスメイトのメディア体験への理解、メディアと自身との関係の考察、グループによる創作活動を通したメディアリテラシー教育を提案する。",
        "workDescriptionEnglish": "This work presents a curriculum design and educational materials for media literacy education in high schools. This research defines media literacy as \"the ability to maintain one's own standards of evaluation when engaging with people and society through media.\" The curriculum aims to bridge individual experience with comprehensive understanding while maintaining connections to society. The proposed approach encompasses four elements: self-reflection on personal media experiences, understanding peers' media interactions, analysis of media-self relationships, and collaborative creative projects",
        "place1": "センタービル12F",
        "place2": "作業室 C1202"
    },
    {
        "studentId": 23118,
        "authorJapaneseName": "松井美緒",
        "authorEnglishName": "Mio Matsui",
        "profileJapanese": "2000年生まれ。慶應義塾大学総合政策学部卒。音響が生む体験に興味を持ち制作している。",
        "profileEnglish": "Born in 2000. Graduated from Keio Univ(SFC). I'm fascinated by sound.",
        "X_URL": "https://x.com/mio427m",
        "instagram_URL": "https://www.instagram.com/mio.mti/",
        "other_URL": "https://miomatsui.notion.site",
        "workTitleJapanese": "残波",
        "workTitleEnglish": "Echoing waves",
        "workDescriptionJapanese": "「ししおどし」を中心とした、暗闇で鑑賞する7分間の作品。\n複製技術時代以降において、W・ベンヤミンは芸術作品の真正性に関わる「アウラの喪失」を指摘した。しかし、現代の情報化/消費化社会の中で「アウラ」は本当に失われたのだろうか？\n複製物のようなまがいものに対しても、受容者の欲望の力によって再びアウラを生み出すことはできないか？\n本作品では、「ししおどし」をトリガーとして、音響の力によって一回きりの「いま、ここ」の体験を提示する。今や和の雰囲気を醸し出す「記号」として固定された「ししおどしのイメージ」の転換を試みる。",
        "workDescriptionEnglish": "This work is a 7-minute piece centered around a \"shishi-odoshi,\" experienced in the dark. In the age of mechanical reproduction, Walter Benjamin pointed out the \"loss of aura\" in artworks related to their authenticity. However, in today's information-driven and consumerist society, has the \"aura\" truly been lost?\nCould the power of the recipient's desires re-create an aura, even for imitations or reproductions?\nThis work takes the \"shishi-odoshi\" as a trigger, presenting a one-time-only experience of \"here and now\" through the power of sound. It seeks to transform the fixed \"image of the shishi-odoshi,\" now established as a \"sign\" evoking a Japanese atmosphere.",
        "place1": "センタービル 4F",
        "place2": "コンピュータ室 C403"
    },
    {
        "studentId": 23120,
        "authorJapaneseName": "山口結子",
        "authorEnglishName": "Yuiko Yamaguchi",
        "profileJapanese": "2000年 宮城県生まれ",
        "profileEnglish": "Born in Miyagi Prefecture in 2000.",
        "X_URL": "",
        "instagram_URL": "",
        "other_URL": "",
        "workTitleJapanese": "Tell You Just Because",
        "workTitleEnglish": "Tell You Just Because",
        "workDescriptionJapanese": "コミュニケーションの気づきをもたらすアニメーション。他者との関わりを身振り手振り、そして間から観察させる空間を創出する。",
        "workDescriptionEnglish": "Animation That Encourages Discovery in Communication. Creating a space that allows the observation of interactions with others through gestures, movements, and the spaces in between.",
        "place1": "センタービル 4F",
        "place2": "講義室1 C411"
    },
    {
        "studentId": 23121,
        "authorJapaneseName": "ジョアンナ リュ",
        "authorEnglishName": "Joanna LYU",
        "profileJapanese": "人々が人間と公共空間、そして社会的な問いとのつながりを探求するインタラクティブな作品の制作に取り組んでいます。",
        "profileEnglish": "Multimedia artist with a background in game dev. Her practice spans across CGI, audiovisual live performances, installations and urban games. She is interested in making interactive works which invite the public to explore the connections between humans, public spaces, and societal questions. ",
        "X_URL": "https://x.com/jyolyu",
        "instagram_URL": "https://www.instagram.com/jyolyyyu/",
        "other_URL": "https://www.joannalyu.com/",
        "workTitleJapanese": "もし…が歌だったら",
        "workTitleEnglish": "if… were a song",
        "workDescriptionJapanese": "「もし…が歌だったら」は、言葉を使って音楽を当てるゲーム。プレイヤーはヒントを受け取り、自分の音楽ライブラリからそのヒントを表現する曲を見つけ出さなければならない。",
        "workDescriptionEnglish": "“If… were a song” is a word-guessing music game.Players receive clues and have to use their own music library to find songs that represents those clues. ",
        "place1": "センタービル12F",
        "place2": "作業室 C1202"
    }
];