export const PROJECT_INFO = [
    {
        "projectName": "The Art of Listenning",
        "representative": "金山智子",
        "sharer": "吉田茂樹、松井茂",
        "assistant": "",
        "projectConcept": "「きくこと」は人が生きていく上での基本的な行為であり、また人と関係する上での土台でもあります。そして「きくこと」は研究や表現活動にとっても重要です。リサーチャー、フィールドワーカー、アーティスト、アーキヴィスト、エンジニアなど多様な人たちが多様な「きくこと」を実践しています。「語り」は、語り手と聞き手の相互行為による共同生成ですが、「語り」に多くの注目が集まり、「きくこと」はあまり議論されてきませんでした。多くの人たちにとって「きくこと」は受動的行為と思われているのかもしれませんし、「きくこと」は過去や現在に関わる行為であり、未来へつながるとはあまり考えられていないのかもしれません。本プロジェクトでは、「きくこと」を表現技法として位置づけ、その方法論や実践、哲学的意義にアプローチすることを通じて、自発的で創造的な行為として考えていきます。",
        "wholeActivityContent1": "2024年度前期は、ネットやSNSによるコミュニケーションに慣れ、人と直接話をする機会が少ない若い世代の履修生たちと会話を重ねながら、「きくこととは何か」を問うことから始めました。特に、知らない人と話すことに慣れていない履修生たちは、7月のオープンハウスでは、現在使用されなくなった公衆電話によるコミュニケーションをテーマにした「顔なしふぉん問答」を企画、面識のない人とのコミュニケーションから「きくこと」の難しさや面白さなどを体験しました。 後期は、メンバーの関心や研究に紐づけながら、以下のようなさまざまな活動を通して「きくこと」を実践し、考察を深めました。\n",
        "wholeActivityContent2": "1. 大地の芸術際越後妻有アートトリエンナーレ　津南エリア（展示鑑賞と秋山地区フィールドワーク)\n2. シンポジウム「世界の中の秋山郷」ティム・インゴルド氏講演会\n3. 「IAMAS顔なしフォン問答」（Ogaki Mini Maker Fair 2024）\n4. 「日々の痕跡としてみるToDoリスト」 ワークショップ (メディアコスモス)\n5. 能登地震被災地視察＆復興ボランティア （石川県珠洲市／能登町）\n6. トークイベント 伊藤雄馬（言語学者）＆マユンキキ（美術家）  (IAMAS2025)\n7. 公開インタビュー　弓指寛治（芸術家）\n",
        "wholeActivityContent3": "古いメディアでのやりとり、地域芸術祭での住民や関係者とのやりとり、能登の被災者たちと　のやりとりといった多様な実践を通して、自分の知覚や感性と、能動的なきくという行為ついて、各自考える機会となりました。また、社会人類学者、美術家、言語学者などの専門家たちの話をきき、他者に伝えていく行為についても、「きくこと」の連関として捉える機会になりました。企画されたワークショップでは、一般的に個人的記録であるTo Do List をもとに語り合うことで、語ることと聴くことの関係性についても再考することになりました。2024年度最後の活動として、これまでのプロジェクト活動を通してつながった美術家や研究者に話をきくトークとインタビューを予定しています。",
        "activityName1": "",
        "activityContent1": "",
        "activityName2": "",
        "activityContent2": "",
        "activityName3": "",
        "activityContent3": "",
        "activityName4": "",
        "activityContent4": "",
        "activityName5": "",
        "activityContent5": "",
        "activityName6": "",
        "activityContent6": "",
        "activityName7": "",
        "activityContent7": "",
        "activityName8": "",
        "activityContent8": "",
        "activityName9": "",
        "activityContent9": "",
        "activityName10": "",
        "activityContent10": "",
        "caption0": "",
        "caption1": "",
        "caption2": "",
        "caption3": "",
        "caption4": ""
    },
    {
        "projectName": "テクノロジーの〈解釈学〉",
        "representative": "小林茂",
        "sharer": "大久保美紀",
        "assistant": "",
        "projectConcept": "人工知能に代表される高度で複雑化したハイテクノロジーは、単なる道具に還元されブラックボックス化されるか、不可避で抗えない変化をもたらすものとして扱われる傾向にあります。そうした立場からの議論では、近代技術や機械技術に基づく今日のテクノロジーは、それ以前の技術から分断されたものとして扱われます。しかしながら、テクノロジー／テクニクスの語源であるテクネー（技術知）は、アルス（芸術）や技芸をも意味する広義の概念であったことを踏まえると、連続的に捉えることもできるはずです。本プロジェクトでは、テクノロジーに関する責任を手放さず、かといって決定論的なものだとして絶望しないための方策として、テクノロジーは誰もが自在に解釈し自分たちのものにできるという考え方に基づく作品群を提示すると共に、それらの作品群と体験者たちの経験を基に「テクノロジーの〈解釈学〉」として理論化することを試みます。",
        "wholeActivityContent1": "初年度は大きく3つの活動に取り組みました。まず、「テクノロジーの〈解釈学〉」と名付けた新しい技術論に関する理論的基盤を探究するため、外部ゲストを招いたシンポジウムを開催しました。このシンポジウムでは、フランス技術論の重要人物ジルベール・シモンドンの研究者で哲学者の宇佐美達朗氏をゲストに招き、〈繭〉を鍵概念とする哲学者エマヌエーレ・コッチャの技術論に関する話題提供を踏まえて議論を深めました。\n",
        "wholeActivityContent2": "また、プロジェクトに参加するメンバーが議論の基盤を構築できるよう、平井靖史『世界は時間でできている——ベルクソン時間哲学入門』（青土社、2022）、ユッシ・パリッカ『メディア考古学とは何か？——デジタル時代のメディア文化研究』（東京大学出版会、2023）、ピーター=ポール・フェルベーク『技術の道徳化——事物の道徳性を理解し設計する』（法政大学出版会、2015）の輪読を行いました。\n",
        "wholeActivityContent3": "さらに、新しい技術論に基づく作品制作の前段階として、Adam Basanta《The sound of empty space》（2015）とPaul DeMarinis《RainDance》（1998）の再制作にも取り組みました。これらの作品は、著名なアーティストの作品としてよく知られており、記録映像や作品を構成するテクノロジカルな要素に関するドキュメントは公開されています。しかしながら、当然のことながらそれらの情報だけを基に作品全体を制作することはできません。限られた情報を基に試行錯誤しながら作品の再制作を試みることは、作品を入口としてテクノロジーに対する理解を深めていくことが求められ、それぞれの作品に特化した〈解釈学〉を構成していく機会にもなります。このほか、展覧会や芸術祭を一緒に視察し、議論を深めました。本発表会では、これら3つの活動の成果より、作品の再制作の成果物を実物と記録映像により展示いたします。シンポジウムの記録動画も公開しておりますので、後ほどご覧ください。",
        "activityName1": "",
        "activityContent1": "",
        "activityName2": "",
        "activityContent2": "",
        "activityName3": "",
        "activityContent3": "",
        "activityName4": "",
        "activityContent4": "",
        "activityName5": "",
        "activityContent5": "",
        "activityName6": "",
        "activityContent6": "",
        "activityName7": "",
        "activityContent7": "",
        "activityName8": "",
        "activityContent8": "",
        "activityName9": "",
        "activityContent9": "",
        "activityName10": "",
        "activityContent10": "",
        "caption0": "2024年7月に開催したシンポジウムの様子",
        "caption1": "シンポジウムの記録動画",
        "caption2": "芸術祭「底に触れる 現代美術 in 瀬戸」視察の様子",
        "caption3": "2024年5月に瑞雲庵（京都市）での展覧会視察後に行ったプロジェクト説明会の様子",
        "caption4": ""
    },
    {
        "projectName": "福祉の技術プロジェクト",
        "representative": "山田晃嗣",
        "sharer": "小林孝浩",
        "assistant": "篠田幸雄",
        "projectConcept": "現代社会においてライフスタイルのみならず、価値観なども多様化しています。そうした現代に生きる中で、時折感じる課題や不具合を技術で解決し、新しい生き方を提案し、希望に満ちた未来を目指します。\n\n本プロジェクトでは、障がい者福祉などに代表される「狭義の福祉」に限定することなく、我々の「身近にある福祉」など幅広い内容を扱っています。\n\n一方で、自然災害の頻度は増加し、被害の規模は拡大しつつあるように思われます。こうした脅威の下、災害から命を守ることはもちろんのこと、災害時にもより前向きに生きられるための技法が必要とされると考えます。このプロジェクトでは「防災」も一つのテーマとして取り組んでいます。\n\nこのプロジェクトではメンバー各自がそれぞれ興味・関心の内容を選択し、フィールドワーク等を行いながら新たな提案をしています。",
        "wholeActivityContent1": "さわれる電子工作応用教具自作用の素材 ‘causal SW’ を提案（篠田幸雄）\n教材自作部（個に適した教材制作に有効と考えるデジタルファブリケーション技術を教育現場へ導入支援する活動）と名付けた自身の活動の一つとして、昨年度よりオリジナルツール‘causal SW’を提案してきました。これは、主に特別支援学校の先生に向けて開発したもので、電子工作の経験がなくても、タッチセンサーや加速度センサーを組み込んで担当児童に向けた教材・教具の自作を容易にするためのプラットフォームです。今年度もワークショップや作例充実化などを実施し、更なる普及を目指しています。",
        "wholeActivityContent2": "",
        "wholeActivityContent3": "",
        "activityName1": "出会い頭事故の体験AR\n\n",
        "activityContent1": "防災に関する活動を大垣特別支援学校の先生と行ってきており、その一環として「出会い頭事故の体験AR」を実施しています。廊下を駆け足で進むと、先生が現れ、音声とともに注意されるARアプリです。予備実験を実施した際に、子どもたちにとってのリアル感、インパクトのある演出が欲しい、という指摘を受け、改良版「廊下での出会い頭事故疑似体験」を計画をしています。\n身体的不器用さのある子どものための、着座姿勢をサポートするプロダクトの提案（三波蒼菜）\n発達障害の一つとして、「発達性協調運動症」（DCD）があります。DCDは体の複数の部位を協調させて動かすことに困難さが現れるという特性があります。ここではDCDなどの身体的に不器用な子どもに焦点を当て、子どもたちの「着座姿勢の保持」をサポートする椅子を提案しました。今回は一人の子供に協力してもらい、学校の給食中に利用する椅子が機能するのかを検証しました。現時点では期間が短いこともあり、着座姿勢に変化は現れませんでしたが、対象生徒の意識に変化を見ることができました。",
        "activityName2": "表情表出の困難さに立ち向かう取組み（牛尾日莉、城戸双汰朗）\n",
        "activityContent2": "子ども向け運動教室に携わった際、表情作りが苦手な児童がいることに気づき、そうした子どもたちも豊かな表情を表出することができれば円滑なコミュニケーションが期待できると考え、今回の取り組みに至りました。表情筋の運動不足や硬直によって、表情作りが困難な場合があると考え、硬直した表情筋をほぐし鍛えるために、目元の動きに着目した表情筋の運動を促すゲームを提案しています。一つは、目元の動きに合わせて単純な図形が変化するもの、もう一つは、目元の動きによって花火が打ち上げられるものです。今は新たなゲームも追加し、ワークショップとして実施することを計画しています。",
        "activityName3": "",
        "activityContent3": "",
        "activityName4": "",
        "activityContent4": "",
        "activityName5": "",
        "activityContent5": "",
        "activityName6": "",
        "activityContent6": "",
        "activityName7": "",
        "activityContent7": "",
        "activityName8": "",
        "activityContent8": "",
        "activityName9": "",
        "activityContent9": "",
        "activityName10": "",
        "activityContent10": "",
        "caption0": "花火が打ち上がり表情筋を鍛えることを目指したアプリ",
        "caption1": "教室での会話の様子",
        "caption2": "causal SW組込み教具の授業実施記録例「もう鬼なんて怖くない」",
        "caption3": "目でバネに触れる体験をするアプリのアイデアスケッチ",
        "caption4": "教室での給食時の様子"
    },
    {
        "projectName": "Collaborative Design Research Project",
        "representative": "鈴木宣也",
        "sharer": "赤羽亨",
        "assistant": "",
        "projectConcept": "社会の課題を発見し、物やシステム開発を通じてそれらを解決しようとするデザイン思考などのデザイン方法論について、2004年頃から事例が増えてきています。しかし、実践する人や経験則、対象とした課題のフレーム自体の設定、あるいは提案した解決方法自体の影響も含め、デザインの方法論自体に関して検証する時期に来ていると考えています。\nまた、消費を前提とした社会に閉塞感を感じ、サスティナビリティへ移行しつつある状況下において、その背景にある社会性や人々の価値観の変化も踏まえ、新たな問いのあり方やデザインプロセスが関わる範囲や影響について模索する必要があると考えています。\nこれまでの原因と結果に基づいた近代的デザイン手法を乗り越えるためにも、全体性やその影響なども含め試行し、デザインする人とデザインする対象との関係を考え、社会とデザインが影響する範囲を検討したいと思い活動しています。",
        "wholeActivityContent1": "地域や企業と対話を進めながら、互いが交差する学外との関係の中で、協働者とのビジョンの共有、プロセスの理解やプロトタイピングも含め、デザインの関わり方について調査・実践しています。具体的には3つの対象をターゲットに活動しています。\n\n",
        "wholeActivityContent2": "",
        "wholeActivityContent3": "",
        "activityName1": "「大垣市」との共同研究＜イアマスこどもだいがく＞\n\n\n",
        "activityContent1": "イアマスこどもだいがくは大垣市との共同研究として小学生向けの情報体験を実施しています。今年度は、プロジェクトメンバーで試作や実験を重ね、糸電話を使って通信コミュニケーションについて遊びながら考える「もしもしワールド」というワークショップをデザインしました。情報伝達のための通信の仕組みや、特殊なコミュニケーションを体感してもらいました。また「伝わる」とはどういうことか、ワークショップを通して、メディアリテラシーについて立ち止まって考える機会となりました。",
        "activityName2": "「飛騨の森でクマは踊る」を中心とする広葉樹の活用に関する調査と提案＜飛騨家具ーパラメトリックデザイン＞\n\n\n",
        "activityContent2": "広葉樹に関する現状を捉えるため、飛騨地方へリサーチトリップを実施しました。広葉樹は針葉樹のように真っ直ぐではなく、また樹種が多く、キャラクターの多さが特徴です。針葉樹と比べ個性が強いため、一点ものの家具に使われることが多く、大量生産の製品の材にはむかないとされています。そこで木々の個性に合わせた展開として、デジタルファブリケーション機器を用いた可能性について、現在、プロトタイプを制作しながら検討しています。",
        "activityName3": "岐阜県に居住する外国人をターゲットに、広告業と共に支援についての実践方法を模索する＜岐阜外国人支援＞\n",
        "activityContent3": "岐阜県庁の「外国人活躍・共生社会推進課」へのヒヤリングを実施し、外国人の現状についての調査をしました。その結果、言葉の壁はもちろんのこと、教育、ライフプラン、キャリア問題など、さまざまな課題があることがわかっています。岐阜県には多様な国々から来た外国人が暮らしているという現状がある一方で、それらの人々は行政との関わり方がわからない、あるいはそもそも接点を持てないという現状にあります。行政の支援を必要としている人々へ、デザインによってどのように関わりを作れるのか、調査しながら、産学官連携を進めています。",
        "activityName4": "",
        "activityContent4": "",
        "activityName5": "",
        "activityContent5": "",
        "activityName6": "",
        "activityContent6": "",
        "activityName7": "",
        "activityContent7": "",
        "activityName8": "",
        "activityContent8": "",
        "activityName9": "",
        "activityContent9": "",
        "activityName10": "",
        "activityContent10": "",
        "caption0": "",
        "caption1": "",
        "caption2": "",
        "caption3": "",
        "caption4": ""
    },
    {
        "projectName": "体験拡張表現プロジェクト",
        "representative": "平林真実",
        "sharer": "前田真二郎、小林孝浩、飛谷謙介",
        "assistant": "",
        "projectConcept": "リアルタイム、インタラクティブな体験には高度なテクノロジーと、テクノロジーを使いこなす表現手法やコンテンツが必要になります。コーディング技術と表現により可能になるクリエイティブコーディングや表現としてのライブコーディングによる音楽や映像を利用した体験やAR、\nMR、 VRといったxR技術により実空間と仮想空間を融合した体験空間の構築、視覚や聴覚以外の各種感覚を用いることによる体験の複合化など、高度な技術と表現による体験拡張は急激に進化しています。本プロジェクトでは、テクノロジーを使いこなし、テクノロジーに適した高度な表現を研究することで、新たな体験拡張の創造を目指します。音楽イベントNxPC.Labの活動と連携することで、研究を展開する場として効果的に利用し、研究・展開を融合した実践的な研究を進めます。",
        "wholeActivityContent1": "プロジェクト最終年度となる本年度は、M1の7名が履修し、体験の拡張を目指した研究・作品を制作しました。東京コンピュータサービス株式会社（現在はマーブル株式会社）とのXR領域の共同研究も行っています。また、サブプロジェクトとしてNxPC.Lab名義の音楽イベントを開催しています。\n\n",
        "wholeActivityContent2": "",
        "wholeActivityContent3": "",
        "activityName1": "IAMASオープンハウスプロジェクト展示\n\n\n",
        "activityContent1": "各々の拡張したい体験を考え修作の展示を行った。マルチカラースイッチングアニメーション、数学xXR、体験型リズムゲーム、生成AIによるドキュメンタリー映像、VR呑み会、自主規制監視体験作品などの展示が行われました。",
        "activityName2": "学会発表\n\n\n",
        "activityContent2": "情報処理学会エンターテインメントコンピューティングシンポジウム(EC2024)\n舞台照明器具を用いたマルチカラースイッチングアニメーションの提案と実験\n鶴目佳蓮（IAMAS）、天野憲樹（ノートルダム清心女子大学）、 平林真実（IAMAS）\nスイッチングアニメーション（赤青アニメ）のマルチカラー化の手法に関する研究のデモ発表を行いました。\n情報処理学会インタラクション2025(3月実施予定）\n生体情報と Avatar を用いた MR 空間における 音楽セッション体験の提案\n伏田昌弘 (株式会社マーブル)、平林真実 (IAMAS)\n共同研究で実施しているXRによるマルチユーザ音楽セッションシステム「AvaPro」についての発表を行います。\n先端音楽創作学会インターカレッジ・ソニックアーツ・フェスティバルに2名の学生が参加し、パフォーマンスと展示を行います。",
        "activityName3": "NxPC.Labの活動 (https://nxpclab.info)\n",
        "activityContent3": "プロジェクトと連携し、音楽、映像、演出等の発表および実験の場として音楽イベント「NxPC.Live」を実施しています。本年度においては、６月の新入生イベント「NxPC.Live\nvol.69 ウィ」、7月のオープンハウスでのイベント「NxPC.Live vol.70\n交通の要所、爆音にて」、本修了制作展におけるイベント「NxPC.Live vol.72\n唵楽と影像」の他、8月には大垣市民プールでの演出への参加、Ogaki Mini Maker Fairと連携したイベント「NxPC.Live\nvol.71 Large Kid Maker」の実施、さらに3月に渋谷Circus Tokyoにてイベントを行う予定になっています。",
        "activityName4": "",
        "activityContent4": "",
        "activityName5": "",
        "activityContent5": "",
        "activityName6": "",
        "activityContent6": "",
        "activityName7": "",
        "activityContent7": "",
        "activityName8": "",
        "activityContent8": "",
        "activityName9": "",
        "activityContent9": "",
        "activityName10": "",
        "activityContent10": "",
        "caption0": "EEEExhibition（ IAMAS OPENHOUSE 2024 ホールA）",
        "caption1": "音楽ゲームのインタラクションで詩を読む作品",
        "caption2": "飲みコミュニケーションに着目したVR作品",
        "caption3": "色分解したグラフィックとスポットライトによるスイッチング・アニメーション",
        "caption4": "生成AIによるムービー作品"
    },
    {
        "projectName": "Extreme Biologies",
        "representative": "Juan Manuel Castro",
        "sharer": "Akitsugu Maebayashi, Mika Kan",
        "assistant": "",
        "projectConcept": "We find ourselves in an era marked by the convergence of biotechnological advances and human culture, a convergence that propels us into uncharted territories. The familiar Darwinian narrative, with its emphasis on biological evolution as the primary driver of change, now gives way to a narrative shaped by the currents of cultural values. We are navigating a “postDarwinian era,” a landscape where the evolution of life is steered not only by the forces of biology but by the intricate interplay of ideas, beliefs, and human agency. In the wake of this paradigmatic shift towards a “postDarwinian era”, this project explores the role of media art in relation to questions of evolution, ecology, global warming, pollution, coexistence, biotechnology and the presence of what we might term “extreme biologies.”",
        "wholeActivityContent1": "",
        "wholeActivityContent2": "",
        "wholeActivityContent3": "",
        "activityName1": " Group discussions on the entanglements of biotechnology and cultural values (June and July)\n",
        "activityContent1": "",
        "activityName2": " Fieldwork to collect moss and microorganisms at Miki Park, Ogaki City (June and July).\n",
        "activityContent2": "",
        "activityName3": " Observation and experiments with moss, tardigrades, nematodes, rotifers, etc. (June and July)\n",
        "activityContent3": "",
        "activityName4": " Exhibition of research activities at IAMAS OPEN HOUSE (July)\n",
        "activityContent4": "",
        "activityName5": " Fieldwork to collect moss and microorganisms around Softopia Japan (September, October).\n",
        "activityContent5": "",
        "activityName6": " Observation and experiments about cryptobiosis (October and November)\n",
        "activityContent6": "",
        "activityName7": " Group discussions on art in collaboration with animals and animal rights (November)\n",
        "activityContent7": "",
        "activityName8": " Fieldwork to collect moss and microorganisms at Yokozo Temple and Kengon Temple, Gifu  (December).\n",
        "activityContent8": "",
        "activityName9": " Group discussions on biotechnology and extreme genetics (December)\n",
        "activityContent9": "",
        "activityName10": " Oral presentation and exhibition of artworks showing the progress achieved during the first year at IAMAS  (January)",
        "activityContent10": "",
        "caption0": "",
        "caption1": "",
        "caption2": "",
        "caption3": "",
        "caption4": ""
    }
];